return {
  kind                 = {
    Class              = "ﴯ",
    Color              = "",
    Constant           = "",
    Constructor        = "",
    Enum               = "",
    EnumMember         = "",
    Event              = "",
    Field              = "ﰠ",
    File               = "",
    Folder             = "",
    Function           = "",
    Interface          = "",
    Keyword            = "",
    Method             = "",
    Module             = "",
    Operator           = "",
    Property           = "ﰠ",
    Reference          = "",
    Snippet            = "",
    Struct             = "",
    Text               = "",
    TypeParameter      = "",
    Unit               = "",
    Value              = "",
    Variable           = "",
  },
  type                 = {
    Array              = "",
    Number             = "",
    String             = "",
    Boolean            = "蘒",
    Object             = "",
  },
  documents            = {
    File               = {
      Default          = "",
      Empty            = "",
    },
    Copy               = "",
    Folder             = {
      Default          = "",
      DefaultOpen      = "",
      Empty            = "",
      EmptyOpen        = "",
      Symlink          = "",
      SymlinkOpen      = "",
    },
  },
  symlink              = {
    Arrow              = "➛",
    File               = "",
    Folder             = "",
  },
  git                  = {
    Add                = "",
    Mod                = "",
    Remove             = "",
    Ignore             = "",
    Rename             = "",
    Diff               = "",
    Repo               = "",
    Octoface           = "",
    Unstaged           = "",
    Staged             = "S",
    Unmerged           = "",
    Renamed            = "➜",
    Untracked          = "U",
    Deleted            = "",
    Ignored            = "◌",
  },
  ui                   = {
    Closed             = "+",
    Open               = "-",
    Lock               = "",
    Circle             = "",
    BigCircle          = "",
    BigUnfilledCircle  = "",
    Close              = "",
    NewFile            = "",
    Search             = "",
    Lightbulb          = "",
    Project            = "",
    Dashboard          = "",
    History            = "",
    Comment            = "",
    Bug                = "",
    Code               = "",
    Telescope          = "",
    Gear               = "",
    Package            = "",
    List               = "",
    SignIn             = "",
    SignOut            = "",
    Check              = "",
    Fire               = "",
    Note               = "",
    BookMark           = "",
    Pencil             = "",
    ChevronRight       = ">",
    Table              = "",
    Calendar           = "",
    CloudDownload      = "",
  },
  diagnostics          = {
    Error              = "",
    Warning            = "",
    Information        = "",
    Question           = "",
    Hint               = "",
  },
  misc                 = {
    Robot              = "ﮧ",
    Squirrel           = "",
    Tag                = "",
    Watch              = "",
    Smiley             = "ﲃ",
    Package            = "",
    CircuitBoard       = "",
  },
  separator            = {
    LeftSeparator      = "",
    RightSeparator     = "",
    ThinLeftSeparator  = "",
    ThinRightSeparator = "",
  },
  blocks               = {
    Diagonal           = {
      LowerLeft        = '🭐',
      UpperRight       = '🭖',
    },
  },
  IndentMarkers        = {
    Corner             = "└",
    Edge               = "│",
  },
}
