return {
  kind                 = {
    Class              = 'ﴯ',
    Color              = '',
    Constant           = '',
    Constructor        = '',
    Enum               = '',
    EnumMember         = '',
    Event              = '',
    Field              = 'ﰠ',
    File               = '',
    Folder             = '',
    Function           = '',
    Interface          = '',
    Keyword            = '',
    Method             = '',
    Module             = '',
    Operator           = '',
    Property           = 'ﰠ',
    Reference          = '',
    Snippet            = '',
    Struct             = '',
    Text               = '',
    TypeParameter      = '',
    Unit               = '',
    Value              = '',
    Variable           = '',
  },
  type                 = {
    Array              = '',
    Boolean            = '蘒',
    Number             = '',
    Object             = '',
    String             = '',
  },
  documents            = {
    File               = {
      Default          = '',
      Empty            = '',
    },
    Copy               = '',
    Folder             = {
      Default          = '',
      DefaultOpen      = '',
      Empty            = '',
      EmptyOpen        = '',
      Symlink          = '',
      SymlinkOpen      = '',
    },
  },
  symlink              = {
    Arrow              = '➛',
    File               = '',
    Folder             = '',
  },
  git                  = {
    Add                = '',
    Deleted            = '',
    Diff               = '',
    Ignore             = '',
    Ignored            = '◌',
    Mod                = '',
    Octoface           = '',
    Remove             = '',
    Rename             = '',
    Renamed            = '➜',
    Repo               = '',
    Staged             = 'S',
    Unmerged           = '',
    Unstaged           = '',
    Untracked          = 'U',
  },
  ui                   = {
    BigCircle          = '',
    BigUnfilledCircle  = '',
    BookMark           = '',
    Bug                = '',
    Calendar           = '',
    Check              = '',
    ChevronRight       = '>',
    Circle             = '',
    Close              = '',
    Closed             = '+',
    CloudDownload      = '',
    Code               = '',
    Comment            = '',
    Dashboard          = '',
    Fire               = '',
    Gear               = '',
    History            = '',
    Lightbulb          = '',
    List               = '',
    Lock               = '',
    NewFile            = '',
    Note               = '',
    Open               = '-',
    Package            = '',
    Pencil             = '',
    Project            = '',
    Search             = '',
    SignIn             = '',
    SignOut            = '',
    Table              = '',
    Telescope          = '',
  },
  diagnostics          = {
    Error              = '',
    Hint               = '',
    Information        = '',
    Question           = '',
    Warning            = '',
  },
  misc                 = {
    CircuitBoard       = '',
    Package            = '',
    Robot              = 'ﮧ',
    Smiley             = 'ﲃ',
    Squirrel           = '',
    Tag                = '',
    Watch              = '',
  },
  separator            = {
    LeftSeparator      = '',
    RightSeparator     = '',
    ThinLeftSeparator  = '',
    ThinRightSeparator = '',
  },
  blocks               = {
    Diagonal           = {
      LowerLeft        = '🭐',
      UpperRight       = '🭖',
    },
  },
  IndentMarkers        = {
    Corner             = '└',
    Edge               = '│',
  },
}
