#!/bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
ROOT_CONFIGS="configs"
CONFIG_PATHS_FILE="symlinks.yml"
source "$ROOT_DIR/$ROOT_CONFIGS/zsh/.zsh/functions/styleText.zsh"
source "$ROOT_DIR/$ROOT_CONFIGS/zsh/.zsh/constants.zsh"
source "$ROOT_DIR/$ROOT_CONFIGS/zsh/.zsh/functions/check_command.zsh"

# Create a temporary PowerShell script
TMP_SCRIPT=$(mktemp -p /tmp wsl_symlink_XXXXXX.ps1)
echo "# Autogenerated symlink creation script ($(date))" > "$TMP_SCRIPT"
# Remove the temporary script when the script exits
trap 'rm -f "$TMP_SCRIPT"' EXIT

DEBUG=${DEBUG:-false}
is_debug() {
  if [ "$DEBUG" = true ]; then
    return 0 # true
  fi
  return 1 # false
}

is_darwin() {
  if [ "$(uname)" = "Darwin" ]; then
    return 0 # true
  fi
  return 1 # false
}

is_wsl() {
  if [ -n "$(grep -i microsoft /proc/version 2>/dev/null)" ] || [ -n "$(grep -i WSL /proc/version 2>/dev/null)" ]; then
    echo "true"
  else
    echo "false"
  fi
}

get_linux_distro() {
  if [ -f "/etc/debian_version" ]; then
    echo "debian"
  else
    echo "all"
  fi
}

printPath() {
  local path="$1"
  echo "$(logCyan -u -- $path)"
}

create_backup() {
  local path="$1"

  $SUDO mv "${path}"{,.bak} 2>/dev/null

  printf "[ $(logGreen "BACK") ] Created $(printPath "${path//\\/\\\\}.bak")\n"
}

remove_old_symlink() {
  local target="$1"

  $SUDO rm "$target"
  printf "[ $(logGreen "DEL") ] Removed old symlink $(printPath "$target")\n"
}

# Get the current WSL distribution name
get_wsl_distro_name() {
  if [ $(is_wsl) = "true" ]; then
    if [ -n "$WSL_DISTRO_NAME" ]; then
      echo "$WSL_DISTRO_NAME"
      return 0
    fi

  local win_root
  win_root=$(wslpath -w / 2>/dev/null)
  local distro_regex='^\\\\wsl(\\\\.localhost)?\\\\([^\\\\]+)\\\\'
  if [[ $win_root =~ $distro_regex ]]; then
      echo "${BASH_REMATCH[2]}"
      return 0
    fi

    grep -oP '(?<=^NAME=").*(?=")' /etc/os-release | tr -d '\r\n'
  fi
}

# Format path for Windows when in WSL
format_wsl_windows_path() {
  local path="$1"
  local distro_name=$(get_wsl_distro_name)

  # Add WSL prefix and replace forward slashes with backslashes
  path="\\\\wsl\$\\$distro_name$path"
  path="${path//\//\\}"

  echo "$path"
}

# This function creates a symbolic link from the source path to the target location
# It handles existing files by creating backups and removes old symlinks if they exist
make_symlink() {
  local path="$1"
  local target="$2"

  local SUDO=''
  local target_dir=$(dirname "$target")

  # Check if we need sudo permissions (if directory is not writable or doesn't exist)
  if [[ ! "$target" =~ "$HOME" ]] || [[ -d "$target_dir" && ! -w "$target_dir" ]] || [[ ! -d "$target_dir" && ! -w "$(dirname "$target_dir")" ]]; then
    SUDO='sudo'
    printf "[ $(logYellow "NOTE") ] Using elevated permissions for $(printPath "$target")\n"
  fi

  # Remove any existing backup of the target if it's a symlink
  if [ -L "${target}.bak" ]; then
    remove_old_symlink "${target}.bak"
  fi

  # Remove old symlink if target already exists as a symbolic link
  if [ -L "$target" ]; then
    remove_old_symlink "$target"
  elif [ -e "$target" ]; then
    # Backup the existing file/directory before creating symlink
    create_backup "$target"
  fi

  # Create parent directory for target if it doesn't exist
  $SUDO mkdir -p $(dirname "$target")

  # Create symbolic link
  if [[ $path =~ "\\\\wsl\$" ]]; then
    logInfo "Creating symlink for WSL: $(printPath "${path//\\/\\\\}")\n"

    # Convert the target path to Windows format
    local win_target=$(wslpath -w "$target" 2>/dev/null)

    # Create a PowerShell script to create the symbolic link
    echo "New-Item -ItemType SymbolicLink -Path '$win_target' -Target '$path' -Force" >> "$TMP_SCRIPT"
  else
    $SUDO ln -s "$path" "$target"
  fi


  logInfo "$(printPath "$target") $(logBlue -b -- $POINTER) $(printPath "${path//\\/\\\\}")\n"
}

first_letter() {
  echo "${1:0:1}"
}

run_elevated_powershell_script() {
  local tmp_script="$1"

  # Skip if no Windows symlink commands were added
  if ! grep -q 'SymbolicLink' "$tmp_script"; then
    logInfo "No Windows symlink operations queued; skipping elevated PowerShell.\n"
    return 0
  fi

  cat "$tmp_script"

  # Convert the path to Windows format
  win_tmp_script=$(wslpath -w "$tmp_script")

  # Run the PowerShell script with elevated privileges
  # - Start-Process: Launches a new PowerShell instance with administrator rights
  # - NoProfile: Skips loading user profile to avoid conflicts
  # - ExecutionPolicy Bypass: Allows script execution without policy restrictions
  # - Verb RunAs: Requests UAC elevation
  # - Wait: Blocks until the elevated process completes
  # - WindowStyle Hidden: Suppresses the PowerShell window
  powershell.exe -NoProfile -Command "Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File \"${win_tmp_script}\"' -Verb RunAs -Wait -WindowStyle Hidden"
}

# Get Windows username when in WSL
get_windows_username() {
  if [ $(is_wsl) = "true" ]; then
    # Try to get Windows username using several methods
    if [ -f /mnt/c/Windows/System32/cmd.exe ]; then
      # Use cmd.exe if available
      /mnt/c/Windows/System32/cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n'
    elif command -v powershell.exe >/dev/null 2>&1; then
      # Use PowerShell if available
      powershell.exe -Command '$env:USERNAME' 2>/dev/null | tr -d '\r'
    elif [ -n "$WSLENV" ] && [ -n "$USERNAME" ]; then
      # Use WSL environment variable if available
      echo "$USERNAME"
    else
      # Fallback to current user
      echo "$USER"
    fi
  else
    # Not in WSL, return current user
    echo "$USER"
  fi
}

build_path_obj() {
  local path="$1"
  local target="$2"
  # Build a JSON object using jq
  json=$(jq -n --arg path "$path" --arg target "$target" '{path: $path, target: $target}')
  echo "$json"
}

get_abs_path() {
  local path="$1"

  if [ "$(first_letter "$path")" != "/" ] && [ "$(first_letter "$path")" != "~" ]; then
    path="$ROOT_CONFIGS/$path"
  fi

  realpath "$path"
}

# Expand environment variables in a path string
expand_env_vars() {
  local path="$1"

  # Replace $HOME with the actual home directory
  path="${path//'$HOME'/$HOME}"
  path="${path//\~/$HOME}"

  # Replace $USER with the appropriate username
  if [[ "$path" == /mnt/c/* ]] || [[ "$path" == WSL://* ]]; then
    # For WSL paths, use Windows username
    path="${path//'$USER'/$USERNAME}"
  else
    # For regular paths, use Linux username
    path="${path//'$USER'/$USER}"
  fi

  echo "$path"
}

add_path_to_output() {
  local path="$1"
  local target="$2"
  local output="$3"

  target="$target"/"$(basename "$path")"

  path=$(get_abs_path "$path")
  if [[ "$target" == WSL://* ]]; then
    # Convert WSL:// prefix to Windows path
    target=${target//WSL:\/\//}
    target="/mnt/c/Users/$USERNAME/$target"
    # WSL paths should use Windows username
    target=$(expand_env_vars "$target")
    path=$(format_wsl_windows_path "$path")
  fi

  local path_obj=$(build_path_obj "$path" "$target")
  echo "$output" | jq -c ". + [$path_obj]"
}

process_path_entry() {
  local line="$1"
  local selector_override="$2"

  local path=$(echo "$line" | jq -r '.path')
  local override_target=$(echo "$line" | jq -r ".overrides[]? | select($selector_override) | .target")
  # Si hay override, úsalo; si no, usa el target normal
  local target=${override_target:-$(echo "$line" | jq -r '.target')}

  if [[ "$target" != WSL://* ]]; then
    if [ "$target" = "null" ]; then
      target="$HOME"
    elif [ "$(first_letter "$target")" != "/" ] && [ "$(first_letter "$target")" != "~" ]; then
      target="$HOME"/"$target"
    fi
  fi

  # Expand environment variables in target path
  target=$(expand_env_vars "$target")

  if is_debug; then
    echo "Path: $(printPath "${path//\\/\\\\}")"
    echo "Target: $(printPath $target)"
    echo "-----------"
  fi

  local output="[]"
  if [[ "$path" == *"*" ]]; then
    # Get the directory path without the asterisk
    local dir_path="${path%/*}"
    local abs_dir_path=$(get_abs_path "$dir_path")

    # Find all files and directories in the specified directory (first level only)
    if [ -d "$abs_dir_path" ]; then
      while IFS= read -r item; do
        # For each item, create a symlink to the target directory
        if is_debug; then
          echo "Item: $(printPath "${item//\\/\\\\}")"
          echo "Target: $(printPath $target)"
          echo "-----------"
        fi
        output=$(add_path_to_output "$item" "$target" "$output")
      done < <(find "$abs_dir_path" -maxdepth 1 -mindepth 1)
    else
      logWarning "Directory not found: $abs_dir_path"
    fi
  else
    output=$(add_path_to_output "$path" "$target" "$output")
  fi

  echo "$output"
}

get_paths() {
  local selector="$1"
  local selector_override="$2"
  local output="[]"

  while read -r line; do
    output=$(echo "$output" | jq -c ". + $(process_path_entry "$line" "$selector_override")")
  done < <(yq eval -o=json ".paths[] | select($selector)" "$CONFIG_PATHS_FILE" | jq -c '.')


  echo "$output"
}

retrieve_linux_paths() {
  local current_distro=$(get_linux_distro)
  local wsl_status=$(is_wsl)

  # Main selector for path entries
  local selector='(
    .excludeFor == null or (.excludeFor[].platform == null and .excludeFor[].wsl != null and .excludeFor[].wsl != '$wsl_status') or (
      .excludeFor[].platform != null and .excludeFor[].platform != "linux" or (
        .excludeFor[].platform == "linux" and (
          (.excludeFor[].linuxDistro != null and .excludeFor[].linuxDistro != "'$current_distro'")
        )
      )
    )
  ) and (
    .onlyFor == null or (.onlyFor[].platform == null and .onlyFor[].wsl != null and .onlyFor[].wsl == '$wsl_status') or (
      .onlyFor[].platform == "linux" and (
        (.onlyFor[].linuxDistro == null or .onlyFor[].linuxDistro == "'$current_distro'")
      )
    )
  )'

  # Selector for overrides specific to this platform
  local selector_override='((.platform == "linux") and
    (.linuxDistro == null or .linuxDistro == "'$current_distro'")) or
    (.platform == null and .wsl != null and .wsl == '$wsl_status')'

  get_paths "$selector" "$selector_override"
}

retrieve_darwin_paths() {
  local selector='(
    .excludeFor == null or .excludeFor[].platform != "darwin"
  ) and (
    .onlyFor == null or .onlyFor[].platform == "darwin"
  )'
  local selector_override='.platform == "darwin"'

  get_paths "$selector" "$selector_override"
}

retrieve_paths_for_platform() {
  if is_darwin; then
    retrieve_darwin_paths
  else
    retrieve_linux_paths
  fi
}

main() {
  check_commands yq jq
  USERNAME=$(get_windows_username)

  local paths="$(retrieve_paths_for_platform)"

  echo "$paths" | jq -c '.[]' | while read -r line; do
    path=$(echo "$line" | jq -r '.path')
    target=$(echo "$line" | jq -r '.target')
    make_symlink "$path" "$target"
  done

  run_elevated_powershell_script $TMP_SCRIPT

  echo "Done!"
}

if [ "$EUID" = 0 ]; then
  logError "Don't run as root!"
  exit 1
fi

if ! is_debug; then
  main
fi
