#!/bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
ROOT_CONFIGS_DIR="$ROOT_DIR/configs"
CONFIG_PATHS_FILE="$ROOT_DIR/symlinks.yml"

for required_source in \
  "$ROOT_CONFIGS_DIR/zsh/.zsh/functions/styleText.zsh" \
  "$ROOT_CONFIGS_DIR/zsh/.zsh/constants.zsh" \
  "$ROOT_CONFIGS_DIR/zsh/.zsh/functions/check_command.zsh"; do
  if [ ! -f "$required_source" ]; then
    printf "[ ERROR ] Falta dependencia requerida: %s\n" "$required_source" >&2
    exit 1
  fi
  # shellcheck source=/dev/null
  source "$required_source"
done
unset required_source

# Create temporary files (template must end with XXXXXX for mktemp portability).
# umask 077 ensures generated files are owner-readable only, hardening against
# tampering on shared /tmp systems before the elevated PowerShell step runs.
DOTFILER_TMP_DIR="${TMPDIR:-/tmp}"
_DOTFILER_PREVIOUS_UMASK=$(umask)
umask 077
TMP_SCRIPT="$(mktemp "${DOTFILER_TMP_DIR%/}/wsl_symlink_XXXXXX")" || {
  echo "Error: could not create temporary script file in ${DOTFILER_TMP_DIR}." >&2
  umask "$_DOTFILER_PREVIOUS_UMASK"
  exit 1
}
FAILED_TARGETS_FILE="$(mktemp "${DOTFILER_TMP_DIR%/}/dotfiler_failed_targets_XXXXXX")" || {
  echo "Error: could not create temporary failure log file in ${DOTFILER_TMP_DIR}." >&2
  rm -f "$TMP_SCRIPT"
  umask "$_DOTFILER_PREVIOUS_UMASK"
  exit 1
}
umask "$_DOTFILER_PREVIOUS_UMASK"
unset _DOTFILER_PREVIOUS_UMASK
echo "# Autogenerated symlink creation script ($(date))" > "$TMP_SCRIPT"
trap 'rm -f "$TMP_SCRIPT" "$FAILED_TARGETS_FILE"' EXIT

DEBUG=${DEBUG:-false}
DRY_RUN=false
USE_COLOR=true
USE_ICONS=true
USE_PATH_STYLE=true
QUIET=false
VERBOSE=false

EXIT_CODE_SUCCESS=0
EXIT_CODE_RUNTIME_ERROR=1
EXIT_CODE_INPUT_ERROR=2

ICON_DELETE=${ICON_DELETE:-"✖"}
ICON_BACKUP=${ICON_BACKUP:-"↺"}
ICON_NOTE=${ICON_NOTE:-"!"}
ICON_LINK=${ICON_LINK:-"⇢"}
ICON_SKIP=${ICON_SKIP:-"⊘"}
ICON_DONE=${ICON_DONE:-"✔"}
ICON_GROUP=${ICON_GROUP:-"▸"}

START_TIME_SECONDS=$(date +%s)
START_TIME_ISO_UTC=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COUNT_CREATED=0
COUNT_REPLACED=0
COUNT_BACKUPS=0
COUNT_SKIPPED=0
COUNT_ERRORS=0
COUNT_WINDOWS_QUEUED=0
COUNT_SUDO_OPERATIONS=0
LAST_OUTPUT_WAS_SEPARATOR=false

is_debug() {
  if [ "$DEBUG" = "true" ]; then
    return 0 # true
  fi
  return 1 # false
}

is_darwin() {
  if [ "$(uname)" = "Darwin" ]; then
    return 0 # true
  fi
  return 1 # false
}

is_wsl() {
  [ -r /proc/version ] || return 1
  grep -qiE 'microsoft|WSL' /proc/version 2>/dev/null
}

get_linux_distro() {
  if [ -f "/etc/debian_version" ]; then
    echo "debian"
  else
    echo "all"
  fi
}

last_argument() {
  printf "%s" "${@: -1}"
}

format_with_style() {
  local formatter="$1"
  shift

  if [ "$USE_COLOR" = "true" ] && command -v "$formatter" >/dev/null 2>&1; then
    "$formatter" "$@"
  else
    last_argument "$@"
  fi
}

print_red() {
  format_with_style "logRed" "$@"
}

print_green() {
  format_with_style "logGreen" "$@"
}

print_yellow() {
  format_with_style "logYellow" "$@"
}

print_blue() {
  format_with_style "logBlue" "$@"
}

print_magenta() {
  format_with_style "logMagenta" "$@"
}

print_gray() {
  format_with_style "logGray" "$@"
}

normalize_display_path() {
  local path="$1"

  if [[ "$path" == *\\* ]]; then
    printf "%s" "$path"
    return 0
  fi

  printf "%s" "$path" | sed -E 's#/+#/#g'
}

abbreviate_home_path() {
  local path="$1"

  if [ -n "$HOME" ] && { [ "$path" = "$HOME" ] || [[ "$path" == "$HOME"/* ]]; }; then
    path="~${path#"$HOME"}"
  fi

  printf "%s" "$path"
}

print_path() {
  local path="$1"
  local normalized_path
  normalized_path=$(normalize_display_path "$path")

  if [ "$USE_PATH_STYLE" = "true" ] && [ "$USE_COLOR" = "true" ] && command -v styleText >/dev/null 2>&1; then
    styleText -u -i -- "$normalized_path"
  else
    printf "%s" "$normalized_path"
  fi
}

build_icon() {
  local icon_value="$1"

  if [ "$USE_ICONS" = "true" ]; then
    printf "%s" "$icon_value"
  fi
}

can_print_details() {
  if [ "$QUIET" = "true" ]; then
    return 1
  fi
  return 0
}

print_link_block_separator() {
  if can_print_details && [ "$LAST_OUTPUT_WAS_SEPARATOR" != "true" ]; then
    printf "%s\n" "$(print_gray -b "────────────────────────────────────────────────────────")"
    LAST_OUTPUT_WAS_SEPARATOR=true
  fi
}

log_info_action() {
  local message="$1"
  if can_print_details; then
    printf "[ %s ] %s\n" "$(print_blue -b "INFO")" "$message"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi
}

log_backup_action() {
  local message="$1"
  if can_print_details; then
    printf "[ %s ] %s %s\n" "$(print_green -b "RESP")" "$(print_green -b "$(build_icon "$ICON_BACKUP")")" "$message"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi
}

log_delete_action() {
  local message="$1"
  if can_print_details; then
    printf "[ %s ] %s %s\n" "$(print_red -b "ELIM")" "$(print_red -b "$(build_icon "$ICON_DELETE")")" "$message"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi
}

log_note_action() {
  local message="$1"
  if can_print_details; then
    printf "[ %s ] %s %s\n" "$(print_yellow -b "NOTA")" "$(print_yellow -b "$(build_icon "$ICON_NOTE")")" "$message"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi
}

log_warn_action() {
  local message="$1"
  printf "[ %s ] %s\n" "$(print_yellow -b "AVISO")" "$message" >&2
  LAST_OUTPUT_WAS_SEPARATOR=false
}

log_error_action() {
  local message="$1"
  printf "[ %s ] %s\n" "$(print_red -b "ERROR")" "$message" >&2
  LAST_OUTPUT_WAS_SEPARATOR=false
}

print_group_header() {
  local group_path="$1"
  if can_print_details; then
    printf "[ %s ] %s %s\n" "$(print_magenta -b "GRUPO")" "$(print_magenta -b "$(build_icon "$ICON_GROUP")")" "$(print_path "$group_path")"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi
}

print_operation_duration() {
  local started_at_seconds="$1"

  if [ "$VERBOSE" = "true" ] && can_print_details; then
    local ended_at_seconds
    ended_at_seconds=$(date +%s)
    local elapsed_seconds=$((ended_at_seconds - started_at_seconds))
    printf "[ %s ] transcurrido=%ss\n" "$(print_gray -b "TIEMPO")" "$elapsed_seconds"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi
}

print_help() {
  cat <<'USAGE'
Uso: ./scripts/dotfiler/dotfiler.sh [opciones]

Opciones:
  --dry-run   Muestra los cambios planificados sin escribir archivos
  --no-color  Desactiva los estilos ANSI
  --plain     Desactiva estilos, íconos y énfasis de rutas
  --verbose   Muestra detalles de tiempo por operación
  --quiet     Oculta logs por ítem y muestra solo resumen/errores
  --help      Muestra esta ayuda
USAGE
}

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
    --dry-run)
      DRY_RUN=true
      ;;
    --no-color)
      USE_COLOR=false
      USE_PATH_STYLE=false
      ;;
    --plain)
      USE_COLOR=false
      USE_ICONS=false
      USE_PATH_STYLE=false
      ;;
    --verbose)
      VERBOSE=true
      ;;
    --quiet)
      QUIET=true
      ;;
    --help)
      print_help
      exit 0
      ;;
    *)
      log_error_action "Opción desconocida: $1"
      print_help
      exit "$EXIT_CODE_INPUT_ERROR"
      ;;
    esac
    shift
  done
}

record_failed_target() {
  local target="$1"
  local reason="$2"
  printf "%s\t%s\n" "$target" "$reason" >> "$FAILED_TARGETS_FILE"
}

# Counts entries persisted in $FAILED_TARGETS_FILE.
# Used to recover failure counts that were incremented inside command
# substitution subshells (e.g. retrieve_paths_for_platform), where
# changes to COUNT_ERRORS are otherwise lost.
recorded_failure_count() {
  if [ ! -s "$FAILED_TARGETS_FILE" ]; then
    echo 0
    return 0
  fi
  awk 'NF { count++ } END { print count + 0 }' "$FAILED_TARGETS_FILE"
}

validate_paths_config() {
  if [ ! -f "$CONFIG_PATHS_FILE" ]; then
    log_error_action "No se encontró el archivo de configuración: $(print_path "$CONFIG_PATHS_FILE")"
    return 1
  fi

  if ! yq eval '.paths' "$CONFIG_PATHS_FILE" >/dev/null 2>&1; then
    log_error_action "Configuración inválida en $(print_path "$CONFIG_PATHS_FILE"): no se pudo interpretar YAML."
    return 1
  fi

  if ! yq eval -o=json '.paths' "$CONFIG_PATHS_FILE" | jq -e 'type == "array"' >/dev/null 2>&1; then
    log_error_action "Configuración inválida en $(print_path "$CONFIG_PATHS_FILE"): 'paths' debe ser un arreglo."
    return 1
  fi

  return 0
}

# Restrict distro name to a conservative charset to prevent path / PowerShell
# injection when the value flows into the elevated script generation.
SAFE_WSL_DISTRO_REGEX='^[A-Za-z0-9._-]+$'

is_safe_wsl_distro_name() {
  [[ "$1" =~ $SAFE_WSL_DISTRO_REGEX ]]
}

# Get the current WSL distribution name
get_wsl_distro_name() {
  is_wsl || return 0

  local candidate=""

  if [ -n "$WSL_DISTRO_NAME" ]; then
    candidate="$WSL_DISTRO_NAME"
  fi

  if [ -z "$candidate" ]; then
    local win_root
    win_root=$(wslpath -w / 2>/dev/null)
    local distro_regex='^\\\\wsl(\\\\.localhost)?\\\\([^\\\\]+)\\\\'
    if [[ $win_root =~ $distro_regex ]]; then
      candidate="${BASH_REMATCH[2]}"
    fi
  fi

  if [ -z "$candidate" ]; then
    candidate=$(awk -F= '/^NAME=/ { gsub(/"/, "", $2); print $2; exit }' /etc/os-release | tr -d '\r\n')
  fi

  if ! is_safe_wsl_distro_name "$candidate"; then
    log_error_action "Nombre de distribución WSL inválido o inseguro: $candidate"
    return 1
  fi

  echo "$candidate"
}

# Format path for Windows when in WSL
format_wsl_windows_path() {
  local path="$1"
  local distro_name
  if ! distro_name=$(get_wsl_distro_name); then
    return 1
  fi

  if ! is_safe_wsl_distro_name "$distro_name"; then
    log_error_action "Nombre de distribución WSL inválido o inseguro: $distro_name"
    return 1
  fi

  path="\\\\wsl\$\\$distro_name$path"
  path="${path//\//\\}"

  echo "$path"
}

# Returns a backup path that does not collide with an existing entry.
# Mirrors Resolve-BackupPath in dotfiler.ps1 so a previous .bak is never overwritten.
resolve_backup_path() {
  local target="$1"
  local candidate="${target}.bak"
  local suffix=1

  while [ -e "$candidate" ] || [ -L "$candidate" ]; do
    candidate="${target}.bak.${suffix}"
    suffix=$((suffix + 1))
  done

  printf "%s" "$candidate"
}

create_backup() {
  local path="$1"
  shift
  local -a command_prefix=("$@")
  local backup_path
  backup_path=$(resolve_backup_path "$path")

  if [ "$DRY_RUN" = "true" ]; then
    COUNT_BACKUPS=$((COUNT_BACKUPS + 1))
    log_backup_action "Crearía $(print_path "${backup_path//\\/\\\\}")"
    return 0
  fi

  if ! "${command_prefix[@]}" mv "${path}" "${backup_path}" 2>/dev/null; then
    log_error_action "No se pudo crear respaldo para $(print_path "$path")"
    record_failed_target "$path" "Fallo al crear respaldo"
    return 1
  fi

  COUNT_BACKUPS=$((COUNT_BACKUPS + 1))
  log_backup_action "Creado $(print_path "${backup_path//\\/\\\\}")"
}

remove_old_symlink() {
  local target="$1"
  shift
  local -a command_prefix=("$@")

  if [ "$DRY_RUN" = "true" ]; then
    log_delete_action "Eliminaría symlink anterior $(print_path "$target")"
    return 0
  fi

  if ! "${command_prefix[@]}" rm "$target"; then
    log_error_action "No se pudo eliminar symlink anterior $(print_path "$target")"
    record_failed_target "$target" "Fallo al eliminar symlink anterior"
    return 1
  fi

  log_delete_action "Symlink anterior eliminado $(print_path "$target")"
}

is_home_path() {
  local path="$1"

  [[ -n "$HOME" && ( "$path" == "$HOME" || "$path" == "$HOME/"* ) ]]
}

find_existing_parent_dir() {
  local path="$1"

  while [ ! -d "$path" ] && [ "$path" != "/" ]; do
    path=$(dirname "$path")
  done

  printf "%s" "$path"
}

needs_elevated_permissions() {
  local target="$1"
  local target_dir="$2"

  if ! is_home_path "$target"; then
    return 0
  fi

  if [ -d "$target_dir" ]; then
    [ ! -w "$target_dir" ]
    return $?
  fi

  local existing_parent_dir
  existing_parent_dir=$(find_existing_parent_dir "$target_dir")

  [ ! -w "$existing_parent_dir" ]
}

# This function creates a symbolic link from the source path to the target location
# It handles existing files by creating backups and removes old symlinks if they exist
make_symlink() {
  local path="$1"
  local target="$2"
  local started_at_seconds
  started_at_seconds=$(date +%s)

  local -a command_prefix=()
  local target_dir
  target_dir=$(dirname "$target")

  if [ "$DRY_RUN" = "true" ]; then
    COUNT_SKIPPED=$((COUNT_SKIPPED + 1))
  fi

  if needs_elevated_permissions "$target" "$target_dir"; then
    command_prefix=(sudo)
    COUNT_SUDO_OPERATIONS=$((COUNT_SUDO_OPERATIONS + 1))
    log_note_action "Usando permisos elevados para $(print_path "$target")"
  fi

  if [ -L "${target}.bak" ]; then
    if ! remove_old_symlink "${target}.bak" "${command_prefix[@]}"; then
      return 1
    fi
  fi

  if [ -L "$target" ]; then
    if ! remove_old_symlink "$target" "${command_prefix[@]}"; then
      return 1
    fi
    COUNT_REPLACED=$((COUNT_REPLACED + 1))
  elif [ -e "$target" ]; then
    if ! create_backup "$target" "${command_prefix[@]}"; then
      return 1
    fi
    COUNT_REPLACED=$((COUNT_REPLACED + 1))
  else
    COUNT_CREATED=$((COUNT_CREATED + 1))
  fi

  if [ "$DRY_RUN" != "true" ]; then
    if ! "${command_prefix[@]}" mkdir -p "$(dirname "$target")"; then
      log_error_action "No se pudo crear directorio padre para $(print_path "$target")"
      record_failed_target "$target" "Fallo al crear directorio padre"
      return 1
    fi
  fi

  if [[ $path =~ "\\\\wsl\$" ]]; then
    log_info_action "$(print_blue -b "$(build_icon "$ICON_LINK")") Preparando destino WSL del symlink $(print_path "${path//\\/\\\\}")"

    if [ "$DRY_RUN" = "true" ]; then
      COUNT_WINDOWS_QUEUED=$((COUNT_WINDOWS_QUEUED + 1))
      log_info_action "$(print_blue -b "$(build_icon "$ICON_SKIP")") Encolaría comando de symlink para Windows"
    else
      local win_target ps_target ps_source
      win_target=$(wslpath -w "$target" 2>/dev/null)
      ps_target="${win_target//\'/\'\'}"
      ps_source="${path//\'/\'\'}"
      echo "New-Item -ItemType SymbolicLink -Path '$ps_target' -Target '$ps_source' -Force" >> "$TMP_SCRIPT"
      COUNT_WINDOWS_QUEUED=$((COUNT_WINDOWS_QUEUED + 1))
    fi
  else
    if [ "$DRY_RUN" = "true" ]; then
      log_info_action "$(print_blue -b "$(build_icon "$ICON_SKIP")") Crearía symlink"
    else
      if ! "${command_prefix[@]}" ln -s "$path" "$target"; then
        log_error_action "No se pudo crear symlink $(print_path "$target") -> $(print_path "${path//\\/\\\\}")"
        record_failed_target "$target" "Fallo al crear symlink"
        return 1
      fi
    fi
  fi

  log_info_action "$(print_blue -b "$(build_icon "$ICON_LINK")") $(print_path "$target") $(print_magenta -b -- "${POINTER}${POINTER}") $(print_path "${path//\\/\\\\}")"
  print_operation_duration "$started_at_seconds"

  return 0
}

first_letter() {
  echo "${1:0:1}"
}

run_elevated_powershell_script() {
  local tmp_script="$1"
  local started_at_seconds
  started_at_seconds=$(date +%s)

  print_link_block_separator

  if ! grep -q 'SymbolicLink' "$tmp_script"; then
    log_info_action "$(print_blue -b "$(build_icon "$ICON_SKIP")") No hay operaciones de symlink para Windows encoladas; se omite PowerShell elevado."
    print_operation_duration "$started_at_seconds"
    return 0
  fi

  if [ "$DRY_RUN" = "true" ]; then
    log_info_action "$(print_blue -b "$(build_icon "$ICON_SKIP")") Modo simulación activo, se omite ejecución de PowerShell elevado."
    print_operation_duration "$started_at_seconds"
    return 0
  fi

  local win_tmp_script
  win_tmp_script=$(wslpath -w "$tmp_script")

  if ! powershell.exe -NoProfile -Command "Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File \"${win_tmp_script}\"' -Verb RunAs -Wait -WindowStyle Hidden"; then
    log_error_action "No se pudo ejecutar el script de PowerShell elevado"
    record_failed_target "powershell_elevado" "Fallo al ejecutar script PowerShell"
    return 1
  fi

  print_operation_duration "$started_at_seconds"
}

# Get Windows username when in WSL
get_windows_username() {
  if ! is_wsl; then
    echo "$USER"
    return 0
  fi

  if [ -f /mnt/c/Windows/System32/cmd.exe ]; then
    /mnt/c/Windows/System32/cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n'
  elif command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -Command '$env:USERNAME' 2>/dev/null | tr -d '\r'
  elif [ -n "$WSLENV" ] && [ -n "$USERNAME" ]; then
    echo "$USERNAME"
  else
    echo "$USER"
  fi
}

build_path_obj() {
  local path="$1"
  local target="$2"
  local json

  json=$(jq -n --arg path "$path" --arg target "$target" '{path: $path, target: $target}')
  echo "$json"
}

json_has_key() {
  local json="$1"
  local key="$2"

  echo "$json" | jq -e --arg key "$key" 'has($key)' >/dev/null 2>&1
}

json_get_value() {
  local json="$1"
  local key="$2"

  echo "$json" | jq -r --arg key "$key" '.[$key]'
}

get_abs_path() {
  local path="$1"

  path=$(expand_env_vars "$path")

  if [ "$(first_letter "$path")" != "/" ] && [ "$(first_letter "$path")" != "~" ]; then
    path="$ROOT_CONFIGS_DIR/$path"
  fi

  realpath "$path" 2>/dev/null || true
}

# Expand environment variables in a path string.
# Only expands `~` when it appears as the leading character so that
# substrings like `archive~backup` are not mangled into `archiveHOMEbackup`.
expand_env_vars() {
  local path="$1"

  path="${path//'$HOME'/$HOME}"
  if [[ "$path" == "~" || "$path" == "~/"* ]]; then
    path="$HOME${path#\~}"
  fi

  if [[ "$path" == /mnt/c/* ]] || [[ "$path" == WSL://* ]]; then
    path="${path//'$USER'/${USERNAME:-$USER}}"
  else
    path="${path//'$USER'/$USER}"
  fi

  echo "$path"
}

add_path_to_output() {
  local path="$1"
  local target="$2"
  local output="$3"
  local uses_exact_target="$4"
  local original_path="$1"
  local selected_target="$target"

  if [ "$uses_exact_target" != "true" ]; then
    selected_target="$target"/"$(basename "$path")"
  fi

  path=$(get_abs_path "$path")
  if [ -z "$path" ]; then
    log_warn_action "Ruta de origen inválida o inexistente: $original_path"
    record_failed_target "$selected_target" "Ruta de origen inexistente"
    echo "$output"
    return 1
  fi

  if [[ "$selected_target" == WSL://* ]]; then
    selected_target=${selected_target//WSL:\/\//}
    selected_target="/mnt/c/Users/$USERNAME/$selected_target"
    selected_target=$(expand_env_vars "$selected_target")
    if ! path=$(format_wsl_windows_path "$path"); then
      record_failed_target "$selected_target" "Nombre de distribución WSL inválido"
      echo "$output"
      return 1
    fi
  fi

  local path_obj
  path_obj=$(build_path_obj "$path" "$selected_target")
  echo "$output" | jq -c ". + [$path_obj]"
}

process_path_entry() {
  local line="$1"
  local selector_override="$2"

  local path
  path=$(echo "$line" | jq -r '.path')
  local selected_override
  selected_override=$(echo "$line" | jq -c "first(.overrides[]? | select($selector_override)) // empty")
  local target
  local uses_exact_target="false"

  if [ -n "$selected_override" ]; then
    if json_has_key "$selected_override" "exactTarget"; then
      target=$(json_get_value "$selected_override" "exactTarget")
      uses_exact_target="true"
    else
      target=$(json_get_value "$selected_override" "target")
    fi
  elif json_has_key "$line" "exactTarget"; then
    target=$(json_get_value "$line" "exactTarget")
    uses_exact_target="true"
  else
    target=$(json_get_value "$line" "target")
  fi

  if [[ "$target" != WSL://* ]]; then
    if [ "$target" = "null" ]; then
      target="$HOME"
    elif [ "$(first_letter "$target")" != "/" ] && [ "$(first_letter "$target")" != "~" ]; then
      target="$HOME"/"$target"
    fi
  fi

  target=$(expand_env_vars "$target")

  if is_debug; then
    echo "Path: $(print_path "${path//\\/\\\\}")" >&2
    echo "Target: $(print_path "$target")" >&2
    echo "-----------" >&2
  fi

  local output="[]"
  if [[ "$path" == *"*" ]]; then
    local dir_path="${path%/*}"
    local abs_dir_path
    abs_dir_path=$(get_abs_path "$dir_path")

    if [ -d "$abs_dir_path" ]; then
      while IFS= read -r item; do
        if is_debug; then
          echo "Item: $(print_path "${item//\\/\\\\}")" >&2
          echo "Target: $(print_path "$target")" >&2
          echo "-----------" >&2
        fi
        output=$(add_path_to_output "$item" "$target" "$output" "$uses_exact_target")
      done < <(find "$abs_dir_path" -maxdepth 1 -mindepth 1)
    else
      log_warn_action "Directorio no encontrado: $abs_dir_path"
    fi
  else
    output=$(add_path_to_output "$path" "$target" "$output" "$uses_exact_target")
  fi

  echo "$output"
}

get_paths() {
  local selector="$1"
  local selector_override="$2"
  local output="[]"

  while read -r line; do
    output=$(echo "$output" | jq -c ". + $(process_path_entry "$line" "$selector_override")")
  done < <(yq eval -o=json ".paths[] | select($selector)" "$CONFIG_PATHS_FILE" | jq -c '.')

  echo "$output"
}

retrieve_linux_paths() {
  local current_distro
  current_distro=$(get_linux_distro)
  local wsl_status="false"
  if is_wsl; then
    wsl_status="true"
  fi

  local selector='(
    .excludeFor == null or (
      [
        .excludeFor[]? |
        select(
          (
            .platform == null and
            .wsl != null and
            .wsl == '$wsl_status'
          ) or (
            .platform == "linux" and
            (.linuxDistro == null or .linuxDistro == "'$current_distro'")
          )
        )
      ] | length == 0
    )
  ) and (
    .onlyFor == null or (
      [
        .onlyFor[]? |
        select(
          (
            .platform == null and
            .wsl != null and
            .wsl == '$wsl_status'
          ) or (
            .platform == "linux" and
            (.linuxDistro == null or .linuxDistro == "'$current_distro'")
          )
        )
      ] | length > 0
    )
  )'

  local selector_override='((.platform == "linux") and
    (.linuxDistro == null or .linuxDistro == "'$current_distro'")) or
    (.platform == null and .wsl != null and .wsl == '$wsl_status')'

  get_paths "$selector" "$selector_override"
}

retrieve_darwin_paths() {
  local selector='(
    .excludeFor == null or ([.excludeFor[]? | select(.platform == "darwin")] | length == 0)
  ) and (
    .onlyFor == null or ([.onlyFor[]? | select(.platform == "darwin")] | length > 0)
  )'
  local selector_override='.platform == "darwin"'

  get_paths "$selector" "$selector_override"
}

retrieve_paths_for_platform() {
  if is_darwin; then
    retrieve_darwin_paths
  else
    retrieve_linux_paths
  fi
}

SUMMARY_METRIC_COLUMN_WIDTH=32
SUMMARY_VALUE_COLUMN_WIDTH=20

_print_summary_format_metric_cell() {
  local metric_label="$1"
  local metric_length=${#metric_label}
  local dots_count=$((SUMMARY_METRIC_COLUMN_WIDTH - metric_length))
  local dots=""

  if [ "$dots_count" -lt 0 ]; then
    dots_count=0
  fi

  while [ "$dots_count" -gt 0 ]; do
    dots="${dots}."
    dots_count=$((dots_count - 1))
  done

  printf "%s%s" "$metric_label" "$dots"
}

_print_summary_format_value_cell() {
  local value_text="$1"
  printf "%-${SUMMARY_VALUE_COLUMN_WIDTH}.${SUMMARY_VALUE_COLUMN_WIDTH}s" "$value_text"
}

print_summary() {
  local end_time_seconds
  end_time_seconds=$(date +%s)
  local end_time_iso_utc
  end_time_iso_utc=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  local total_elapsed_seconds=$((end_time_seconds - START_TIME_SECONDS))
  local status_value="[OK] Sin errores"
  local execution_mode="Aplicación real"

  if [ "$COUNT_ERRORS" -gt 0 ]; then
    status_value="[X] Con errores"
  fi

  if [ "$DRY_RUN" = "true" ]; then
    execution_mode="Simulación"
  fi

  print_link_block_separator
  printf "%s\n" "$(print_blue -b "RESUMEN")"
  LAST_OUTPUT_WAS_SEPARATOR=false
  printf "%s\n" "$(print_gray -b "╔══════════════════════════════════╦══════════════════════╗")"
  printf "%s\n" "$(print_gray -b "║ Métrica                          ║ Valor                ║")"
  printf "%s\n" "$(print_gray -b "╠══════════════════════════════════╬══════════════════════╣")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Inicio (UTC)") ║ $(_print_summary_format_value_cell "$START_TIME_ISO_UTC") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Fin (UTC)") ║ $(_print_summary_format_value_cell "$end_time_iso_utc") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Tiempo total (s)") ║ $(_print_summary_format_value_cell "$total_elapsed_seconds") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Modo ejecución") ║ $(_print_summary_format_value_cell "$execution_mode") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Creados") ║ $(_print_summary_format_value_cell "$COUNT_CREATED") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Reemplazados") ║ $(_print_summary_format_value_cell "$COUNT_REPLACED") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Respaldos") ║ $(_print_summary_format_value_cell "$COUNT_BACKUPS") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Omitidos") ║ $(_print_summary_format_value_cell "$COUNT_SKIPPED") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Ops. con sudo") ║ $(_print_summary_format_value_cell "$COUNT_SUDO_OPERATIONS") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Ops. Windows en cola (PS)") ║ $(_print_summary_format_value_cell "$COUNT_WINDOWS_QUEUED") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Errores") ║ $(_print_summary_format_value_cell "$COUNT_ERRORS") ║")"
  printf "%s\n" "$(print_gray -b "║ $(_print_summary_format_metric_cell "Estado") ║ $(_print_summary_format_value_cell "$status_value") ║")"
  printf "%s\n" "$(print_gray -b "╚══════════════════════════════════╩══════════════════════╝")"

  if [ "$DRY_RUN" = "true" ]; then
    printf "[ %s ] Modo simulación activo, no se escribieron cambios en el sistema de archivos.\n" "$(print_blue -b "INFO")"
    LAST_OUTPUT_WAS_SEPARATOR=false
  fi

  print_link_block_separator

  if [ "$COUNT_ERRORS" -eq 0 ]; then
    printf "[ %s ] %s Configuración de symlinks finalizada.\n" "$(print_green -b "FIN")" "$(print_green -b "$(build_icon "$ICON_DONE")")"
  else
    printf "[ %s ] Finalizado con %s error(es).\n" "$(print_red -b "FIN")" "$COUNT_ERRORS"
  fi
  LAST_OUTPUT_WAS_SEPARATOR=false
}

print_diagnostics() {
  if [ ! -s "$FAILED_TARGETS_FILE" ]; then
    return 0
  fi

  print_link_block_separator
  printf "%s\n" "$(print_blue -b "DIAGNÓSTICO")"
  LAST_OUTPUT_WAS_SEPARATOR=false

  local diagnostic_index=1
  while IFS=$'\t' read -r failed_target failed_reason; do
    [ -z "$failed_target" ] && continue
    printf "[ %s ] %s) destino=%s | causa=%s\n" \
      "$(print_red -b "ERROR")" \
      "$diagnostic_index" \
      "$(print_path "$failed_target")" \
      "$failed_reason"
    diagnostic_index=$((diagnostic_index + 1))
    LAST_OUTPUT_WAS_SEPARATOR=false
  done < "$FAILED_TARGETS_FILE"
}

main() {
  parse_args "$@"

  check_commands yq jq
  if ! validate_paths_config; then
    print_diagnostics
    return "$EXIT_CODE_INPUT_ERROR"
  fi

  USERNAME=$(get_windows_username)

  local paths
  paths="$(retrieve_paths_for_platform)"
  local is_first_link="true"
  local last_group=""

  print_link_block_separator

  while read -r line; do
    if [ -z "$line" ]; then
      continue
    fi

    local path
    path=$(echo "$line" | jq -r '.path')
    local target
    target=$(echo "$line" | jq -r '.target')

    local current_group
    current_group=$(dirname "$target")
    current_group=$(abbreviate_home_path "$current_group")

    if [ "$current_group" != "$last_group" ]; then
      if [ "$is_first_link" != "true" ]; then
        print_link_block_separator
      fi
      print_group_header "$current_group"
      last_group="$current_group"
    fi

    if ! make_symlink "$path" "$target"; then
      COUNT_ERRORS=$((COUNT_ERRORS + 1))
      log_error_action "La operación falló para el destino $(print_path "$target")"
    fi

    is_first_link="false"
  done < <(echo "$paths" | jq -c '.[]')

  if [ "$is_first_link" = "false" ]; then
    print_link_block_separator
  fi

  if ! run_elevated_powershell_script "$TMP_SCRIPT"; then
    COUNT_ERRORS=$((COUNT_ERRORS + 1))
  fi

  # Reconcile errors recorded inside command substitution subshells
  # (e.g. add_path_to_output during retrieve_paths_for_platform) so that
  # the summary and exit code reflect failures that the in-process
  # COUNT_ERRORS counter could not observe.
  local recorded_failures
  recorded_failures=$(recorded_failure_count)
  if [ "$recorded_failures" -gt "$COUNT_ERRORS" ]; then
    COUNT_ERRORS="$recorded_failures"
  fi

  print_summary
  print_diagnostics

  if [ "$COUNT_ERRORS" -gt 0 ]; then
    return "$EXIT_CODE_RUNTIME_ERROR"
  fi

  return "$EXIT_CODE_SUCCESS"
}

if [ "$EUID" = 0 ]; then
  log_error_action "No ejecutes este script como root."
  exit "$EXIT_CODE_INPUT_ERROR"
fi

main "$@"
