#!/bin/bash

ROOT_DIR="$(git rev-parse --show-toplevel)"
ROOT_CONFIGS_DIR="$ROOT_DIR/configs"
CONFIG_PATHS_FILE="$ROOT_DIR/symlinks.yml"

for required_source in \
  "$ROOT_CONFIGS_DIR/zsh/.zsh/functions/styleText.zsh" \
  "$ROOT_CONFIGS_DIR/zsh/.zsh/constants.zsh" \
  "$ROOT_CONFIGS_DIR/zsh/.zsh/functions/check_command.zsh"; do
  if [ ! -f "$required_source" ]; then
    printf "[ ERROR ] Falta dependencia requerida: %s\n" "$required_source" >&2
    exit 1
  fi
  # shellcheck source=/dev/null
  source "$required_source"
done
unset required_source

# Create temporary files (template must end with XXXXXX for mktemp portability).
# umask 077 ensures generated files are owner-readable only, hardening against
# tampering on shared /tmp systems before the elevated PowerShell step runs.
DOTFILER_TMP_DIR="${TMPDIR:-/tmp}"
_DOTFILER_PREVIOUS_UMASK=$(umask)
umask 077
TMP_SCRIPT="$(mktemp "${DOTFILER_TMP_DIR%/}/wsl_symlink_XXXXXX")" || {
  echo "Error: could not create temporary script file in ${DOTFILER_TMP_DIR}." >&2
  umask "$_DOTFILER_PREVIOUS_UMASK"
  exit 1
}
FAILED_TARGETS_FILE="$(mktemp "${DOTFILER_TMP_DIR%/}/dotfiler_failed_targets_XXXXXX")" || {
  echo "Error: could not create temporary failure log file in ${DOTFILER_TMP_DIR}." >&2
  rm -f "$TMP_SCRIPT"
  umask "$_DOTFILER_PREVIOUS_UMASK"
  exit 1
}
umask "$_DOTFILER_PREVIOUS_UMASK"
unset _DOTFILER_PREVIOUS_UMASK
echo "# Autogenerated symlink creation script ($(date))" > "$TMP_SCRIPT"
RESOLVE_PROGRESS_FILE="$(mktemp "${DOTFILER_TMP_DIR%/}/dotfiler_progress_XXXXXX")" || {
  echo "Error: could not create temporary progress file in ${DOTFILER_TMP_DIR}." >&2
  rm -f "$TMP_SCRIPT" "$FAILED_TARGETS_FILE"
  exit 1
}
trap 'stop_spinner; rm -f "$TMP_SCRIPT" "$FAILED_TARGETS_FILE" "$RESOLVE_PROGRESS_FILE"' EXIT

DEBUG=${DEBUG:-false}
DRY_RUN=false
USE_COLOR=true
USE_ICONS=true
USE_PATH_STYLE=true
QUIET=false
VERBOSE=false

EXIT_CODE_SUCCESS=0
EXIT_CODE_RUNTIME_ERROR=1
EXIT_CODE_INPUT_ERROR=2

# Emojis without variation selectors: each one is a single character that
# terminals render two columns wide, which keeps columns aligned.
ICON_APP=${ICON_APP:-"🔗"}
ICON_REAL_RUN=${ICON_REAL_RUN:-"🚀"}
ICON_DRY_RUN=${ICON_DRY_RUN:-"🧪"}
ICON_SOURCE=${ICON_SOURCE:-"📦"}
ICON_HOME=${ICON_HOME:-"🏠"}
ICON_GROUP=${ICON_GROUP:-"📁"}
ICON_CREATED=${ICON_CREATED:-"✨"}
ICON_REPLACED=${ICON_REPLACED:-"🔄"}
ICON_UNCHANGED=${ICON_UNCHANGED:-"✅"}
ICON_DELETE=${ICON_DELETE:-"🧹"}
ICON_BACKUP=${ICON_BACKUP:-"💾"}
ICON_DIRECTORY=${ICON_DIRECTORY:-"📂"}
ICON_SUDO=${ICON_SUDO:-"🔐"}
ICON_QUEUED=${ICON_QUEUED:-"🪟"}
ICON_WARN=${ICON_WARN:-"🚨"}
ICON_ERROR=${ICON_ERROR:-"❌"}
ICON_TIME=${ICON_TIME:-"⌛"}
ICON_SUMMARY=${ICON_SUMMARY:-"📊"}
ICON_DIAGNOSTIC=${ICON_DIAGNOSTIC:-"🩺"}
ICON_DONE=${ICON_DONE:-"🎉"}
ICON_FAILED=${ICON_FAILED:-"💥"}

BOX_TOP_LEFT="╭"
BOX_BOTTOM_LEFT="╰"
BOX_VERTICAL="│"
BOX_TEE="├"
BOX_HORIZONTAL="─"
BOX_RULE_WIDTH=64

# Progress feedback: auto (only on an interactive terminal), always or never.
DOTFILER_PROGRESS=${DOTFILER_PROGRESS:-auto}
SPINNER_FRAMES=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
SPINNER_TICK_SECONDS=0.1
SPINNER_TICKS_PER_MESSAGE=20
PROGRESS_BAR_WIDTH=12
PROGRESS_BAR_FILLED="▰"
PROGRESS_BAR_EMPTY="▱"
PROGRESS_DETAIL_MAX_LENGTH=36
RESOLVE_MESSAGE_ICONS=("🧭" "🧩" "🔎" "🧹" "☕")
RESOLVE_MESSAGE_TEXTS=("Resolviendo rutas" "Recorriendo agrupadores" "Aplicando filtros" "Buscando enlaces obsoletos" "Ya casi")
ICON_LINKING=${ICON_LINKING:-"🔗"}
# Decoration mode: emoji (default), unicode (--unicode, no emojis) or ascii
# (--ascii). Chosen only by flags; the flags are mutually exclusive.
ICON_MODE="emoji"
DISPLAY_SEPARATOR="·"
DISPLAY_ELLIPSIS="…"
SPINNER_PID=""
STATUS_LINE_ACTIVE="false"

ACTION_LABEL_WIDTH=12
MIN_ITEM_NAME_WIDTH=16
MAX_ITEM_NAME_WIDTH=40
# Groups operations by destination folder (stable, so config order is kept
# inside each group) to print each folder header once.
SORT_BY_TARGET_GROUP_FILTER='sort_by(.target | gsub("/+"; "/") | gsub("/\\./"; "/") | sub("/[^/]*$"; "")) | .[]'
ITEM_NAME_WIDTH=$MIN_ITEM_NAME_WIDTH

LINK_TYPE_SYMLINK="symlink"
LINK_TYPE_HARD="hard link"
POWERSHELL_LINK_TYPE_SYMLINK="SymbolicLink"
POWERSHELL_LINK_TYPE_HARD="HardLink"

START_TIME_SECONDS=$(date +%s)
COUNT_CREATED=0
COUNT_REPLACED=0
COUNT_REMOVED=0
COUNT_BACKUPS=0
COUNT_UNCHANGED=0
GROUP_UNCHANGED_COUNT=0
COUNT_ERRORS=0
COUNT_WINDOWS_QUEUED=0
COUNT_SUDO_OPERATIONS=0
PLANNED_DIRECTORY_REPLACEMENTS=$'\n'
LAST_OUTPUT_WAS_BLANK=true
PENDING_GROUP_HEADER=""
GROUP_CHANGE_COUNT=0
LAST_GROUP_OPEN="false"

is_debug() {
  if [ "$DEBUG" = "true" ]; then
    return 0 # true
  fi
  return 1 # false
}

is_darwin() {
  if [ "$(uname)" = "Darwin" ]; then
    return 0 # true
  fi
  return 1 # false
}

is_wsl() {
  [ -r /proc/version ] || return 1
  grep -qiE 'microsoft|WSL' /proc/version 2>/dev/null
}

get_linux_distro() {
  if [ -f "/etc/debian_version" ]; then
    echo "debian"
  else
    echo "all"
  fi
}

last_argument() {
  printf "%s" "${@: -1}"
}

format_with_style() {
  local formatter="$1"
  shift

  if [ "$USE_COLOR" = "true" ] && command -v "$formatter" >/dev/null 2>&1; then
    "$formatter" "$@"
  else
    last_argument "$@"
  fi
}

print_red() {
  format_with_style "logRed" "$@"
}

print_green() {
  format_with_style "logGreen" "$@"
}

print_yellow() {
  format_with_style "logYellow" "$@"
}

print_blue() {
  format_with_style "logBlue" "$@"
}

print_magenta() {
  format_with_style "logMagenta" "$@"
}

print_gray() {
  format_with_style "logGray" "$@"
}

normalize_display_path() {
  local path="$1"

  if [[ "$path" == *\\* ]]; then
    printf "%s" "$path"
    return 0
  fi

  printf "%s" "$path" | sed -E -e 's#/+#/#g' -e ':collapse' -e 's#/\./#/#' -e 't collapse' -e 's#(.)/\.$#\1#'
}

abbreviate_home_path() {
  local path="$1"
  local home_path

  for home_path in "$HOME" "$(realpath "$HOME" 2>/dev/null)"; do
    [ -z "$home_path" ] && continue
    if [ "$path" = "$home_path" ] || [[ "$path" == "$home_path"/* ]]; then
      printf "%s" "~${path#"$home_path"}"
      return 0
    fi
  done

  printf "%s" "$path"
}

print_path() {
  local path="$1"
  local normalized_path
  normalized_path=$(normalize_display_path "$path")

  if [ "$USE_PATH_STYLE" = "true" ] && [ "$USE_COLOR" = "true" ] && command -v styleText >/dev/null 2>&1; then
    styleText -u -i -- "$normalized_path"
  else
    printf "%s" "$normalized_path"
  fi
}

build_icon() {
  local icon_value="$1"

  if [ "$USE_ICONS" = "true" ]; then
    printf "%s" "$icon_value"
  fi
}

can_print_details() {
  if [ "$QUIET" = "true" ]; then
    return 1
  fi
  return 0
}

# Pads text to a width counted in characters (printf pads by bytes, which
# misaligns accented text).
pad_text() {
  local text="$1"
  local width="$2"
  local padding=$((width - ${#text}))

  if [ "$padding" -le 0 ]; then
    printf "%s" "$text"
    return 0
  fi
  printf "%s%*s" "$text" "$padding" ""
}

display_target_path() {
  normalize_display_path "$(abbreviate_home_path "$1")"
}

# Shows sources relative to the repository configs directory, or with `~`
# for paths inside HOME.
display_source_path() {
  local path="$1"

  if [[ "$path" == "$ROOT_CONFIGS_DIR/"* ]]; then
    path="${path#"$ROOT_CONFIGS_DIR/"}"
  else
    path=$(abbreviate_home_path "$path")
  fi

  normalize_display_path "$path"
}

# Prints an emoji followed by a space, or nothing with --plain.
icon_prefix() {
  if [ "$USE_ICONS" = "true" ] && [ -n "$1" ]; then
    printf "%s " "$1"
  fi
}

repeat_text() {
  local text="$1"
  local count="$2"
  local result=""
  while [ "$count" -gt 0 ]; do
    result="$result$text"
    count=$((count - 1))
  done
  printf "%s" "$result"
}

# Boxes are open on the right: emoji width varies between terminals, so only
# the left border and the horizontal rules are drawn.
print_box_top() {
  clear_status_line
  local title="$1"
  local title_length=${#title}
  local rule_length=$((BOX_RULE_WIDTH - title_length - 4))
  if [ -z "$title" ]; then
    printf "%s\n" "$(print_gray -b "$BOX_TOP_LEFT$(repeat_text "$BOX_HORIZONTAL" "$BOX_RULE_WIDTH")")"
    return 0
  fi
  printf "%s %s %s\n" \
    "$(print_gray -b "$BOX_TOP_LEFT$BOX_HORIZONTAL")" \
    "$(print_blue -b "$title")" \
    "$(print_gray -b "$(repeat_text "$BOX_HORIZONTAL" "$rule_length")")"
}

print_box_row() {
  clear_status_line
  printf "%s %s\n" "$(print_gray -b "$BOX_VERTICAL")" "$1"
}

print_box_divider() {
  clear_status_line
  printf "%s\n" "$(print_gray -b "$BOX_TEE$(repeat_text "$BOX_HORIZONTAL" "$BOX_RULE_WIDTH")")"
}

print_box_bottom() {
  clear_status_line
  printf "%s\n" "$(print_gray -b "$BOX_BOTTOM_LEFT$(repeat_text "$BOX_HORIZONTAL" "$BOX_RULE_WIDTH")")"
}

progress_is_enabled() {
  case "$DOTFILER_PROGRESS" in
  always) return 0 ;;
  never) return 1 ;;
  esac
  [ "$QUIET" != "true" ] && [ "$DEBUG" != "true" ] && [ -t 2 ]
}

clear_status_line() {
  if [ "$STATUS_LINE_ACTIVE" = "true" ]; then
    printf "\r\033[K" >&2
    STATUS_LINE_ACTIVE="false"
  fi
}

truncate_text() {
  local text="$1"
  local max_length="$2"
  if [ "${#text}" -le "$max_length" ]; then
    printf "%s" "$text"
    return 0
  fi
  printf "%s%s" "${text:0:$((max_length - ${#DISPLAY_ELLIPSIS}))}" "$DISPLAY_ELLIPSIS"
}

build_progress_bar() {
  local current="$1"
  local total="$2"
  local filled=0
  if [ "$total" -gt 0 ]; then
    filled=$((current * PROGRESS_BAR_WIDTH / total))
  fi
  printf "%s%s" "$(repeat_text "$PROGRESS_BAR_FILLED" "$filled")" "$(repeat_text "$PROGRESS_BAR_EMPTY" $((PROGRESS_BAR_WIDTH - filled)))"
}

# Renders one status line on stderr: spinner frame, message, progress bar,
# counter, current item and elapsed seconds. It is overwritten in place.
render_status_line() {
  local frame="$1"
  local icon="$2"
  local message="$3"
  local current="$4"
  local total="$5"
  local detail="$6"
  local elapsed_seconds="$7"

  local progress_text=""
  if [ -n "$total" ] && [ "$total" -gt 0 ]; then
    progress_text=" $(print_blue -b "$(build_progress_bar "$current" "$total")") $current/$total"
  fi
  local detail_text=""
  if [ -n "$detail" ]; then
    detail_text=" $(print_gray -b "$DISPLAY_SEPARATOR $(truncate_text "$detail" "$PROGRESS_DETAIL_MAX_LENGTH")")"
  fi
  local elapsed_text=""
  if [ -n "$elapsed_seconds" ]; then
    elapsed_text=" $(print_gray -b "$(icon_prefix "$ICON_TIME")${elapsed_seconds}s")"
  fi

  printf "\r\033[K%s %s%s%s%s" "$(print_magenta -b "$frame")" "$(icon_prefix "$icon")$message" "$progress_text" "$detail_text" "$elapsed_text" >&2
}

# Animates a spinner in the background while paths are resolved. Messages
# rotate every few seconds and the current entry is read from a progress file
# written by get_paths.
start_spinner() {
  progress_is_enabled || return 0
  printf "\033[?25l" >&2

  (
    trap 'exit 0' TERM
    local tick=0
    local started_at_seconds
    started_at_seconds=$(date +%s)
    local frame_count=${#SPINNER_FRAMES[@]}
    local message_count=${#RESOLVE_MESSAGE_TEXTS[@]}
    local progress_line current total detail
    while true; do
      local message_index=$(((tick / SPINNER_TICKS_PER_MESSAGE) % message_count))
      progress_line=""
      if [ -s "$RESOLVE_PROGRESS_FILE" ]; then
        IFS= read -r progress_line < "$RESOLVE_PROGRESS_FILE"
      fi
      current="${progress_line%%/*}"
      total="${progress_line#*/}"
      total="${total%% *}"
      detail="${progress_line#* }"
      if [ -z "$progress_line" ]; then
        current=""
        total=""
        detail=""
      fi
      render_status_line "${SPINNER_FRAMES[$((tick % frame_count))]}" \
        "${RESOLVE_MESSAGE_ICONS[$message_index]}" "${RESOLVE_MESSAGE_TEXTS[$message_index]}" \
        "$current" "$total" "$detail" "$(($(date +%s) - started_at_seconds))"
      sleep "$SPINNER_TICK_SECONDS"
      tick=$((tick + 1))
    done
  ) &
  SPINNER_PID=$!
  STATUS_LINE_ACTIVE="true"
}

stop_spinner() {
  if [ -n "$SPINNER_PID" ]; then
    kill "$SPINNER_PID" 2>/dev/null
    wait "$SPINNER_PID" 2>/dev/null
    SPINNER_PID=""
    STATUS_LINE_ACTIVE="true"
  fi
  clear_status_line
  if progress_is_enabled; then
    printf "\033[?25h" >&2
  fi
}

# Synchronous progress for the linking loop: redrawn before each operation and
# cleared by any regular output line.
render_linking_progress() {
  local current="$1"
  local total="$2"
  local item_name="$3"
  progress_is_enabled || return 0
  render_status_line "${SPINNER_FRAMES[$((current % ${#SPINNER_FRAMES[@]}))]}" \
    "$ICON_LINKING" "Enlazando" "$current" "$total" "$item_name" ""
  STATUS_LINE_ACTIVE="true"
}

# Prints one operation line: icon, action label, item name and optional detail.
print_item_line() {
  local color_function="$1"
  local icon="$2"
  local label="$3"
  local name="$4"
  local detail="${5:-}"

  can_print_details || return 0
  print_pending_group_header
  GROUP_CHANGE_COUNT=$((GROUP_CHANGE_COUNT + 1))

  local item_text="$name"
  if [ -n "$detail" ]; then
    item_text="$(pad_text "$name" "$ITEM_NAME_WIDTH") $(print_gray -b "$detail")"
  fi

  print_box_row "$(icon_prefix "$icon")$("$color_function" -b "$(pad_text "$label" "$ACTION_LABEL_WIDTH")") $item_text"
  LAST_OUTPUT_WAS_BLANK=false
}

print_link_detail() {
  local source_path="$1"
  local link_type="$2"
  local detail
  detail="$POINTER $(display_source_path "$source_path")"
  if [ "$link_type" = "$LINK_TYPE_HARD" ]; then
    detail="$detail ($LINK_TYPE_HARD)"
  fi
  printf "%s" "$detail"
}

print_block_gap() {
  if can_print_details && [ "$LAST_OUTPUT_WAS_BLANK" != "true" ]; then
    clear_status_line
    printf "\n"
    LAST_OUTPUT_WAS_BLANK=true
  fi
}

log_info_action() {
  local message="$1"
  clear_status_line
  if can_print_details; then
    printf "  %s\n" "$(print_gray -b "$message")"
    LAST_OUTPUT_WAS_BLANK=false
  fi
}




log_warn_action() {
  local message="$1"
  clear_status_line
  printf "%s %s\n" "$(print_yellow -b "$(icon_prefix "$ICON_WARN")Aviso:")" "$message" >&2
  LAST_OUTPUT_WAS_BLANK=false
}

log_error_action() {
  local message="$1"
  clear_status_line
  printf "%s %s\n" "$(print_red -b "$(icon_prefix "$ICON_ERROR")Error:")" "$message" >&2
  LAST_OUTPUT_WAS_BLANK=false
}

# Registers the group header; it is printed lazily before the first visible
# line of the group, so groups where nothing changed stay hidden.
print_group_header() {
  PENDING_GROUP_HEADER="$1"
  if [ "$VERBOSE" = "true" ]; then
    print_pending_group_header
  fi
}

print_pending_group_header() {
  if [ -z "$PENDING_GROUP_HEADER" ] || ! can_print_details; then
    return 0
  fi

  local group_path="$PENDING_GROUP_HEADER"
  PENDING_GROUP_HEADER=""
  GROUP_CHANGE_COUNT=0
  LAST_GROUP_OPEN="true"
  print_block_gap
  clear_status_line
  printf "%s\n" "$(print_magenta -b "$(icon_prefix "$ICON_GROUP")$(normalize_display_path "$group_path")")"
  LAST_OUTPUT_WAS_BLANK=false
}

# Prints the aggregated count of links that were already correct in the
# current group, only when the group also had visible changes. With
# --verbose each unchanged link is listed instead.
# Closes the current group box with its change and unchanged counts. Groups
# where nothing changed were never opened, unless --verbose is active.
flush_group_unchanged_count() {
  if [ -z "$PENDING_GROUP_HEADER" ] && [ "$LAST_GROUP_OPEN" = "true" ] && can_print_details; then
    local closing_parts=()
    if [ "$VERBOSE" != "true" ] && [ "$GROUP_CHANGE_COUNT" -gt 0 ]; then
      closing_parts+=("$GROUP_CHANGE_COUNT $(pluralize "$GROUP_CHANGE_COUNT" "cambio" "cambios")")
    fi
    if [ "$GROUP_UNCHANGED_COUNT" -gt 0 ]; then
      closing_parts+=("$(icon_prefix "$ICON_UNCHANGED")$GROUP_UNCHANGED_COUNT sin cambios")
    fi

    local closing_text=""
    local closing_part
    for closing_part in "${closing_parts[@]}"; do
      if [ -z "$closing_text" ]; then
        closing_text="$closing_part"
      else
        closing_text="$closing_text $DISPLAY_SEPARATOR $closing_part"
      fi
    done
    clear_status_line
    printf "%s %s\n" "$(print_gray -b "$BOX_BOTTOM_LEFT$BOX_HORIZONTAL")" "$(print_gray -b "$closing_text")"
    LAST_OUTPUT_WAS_BLANK=false
  fi
  GROUP_UNCHANGED_COUNT=0
  GROUP_CHANGE_COUNT=0
  PENDING_GROUP_HEADER=""
  LAST_GROUP_OPEN="false"
}

pluralize() {
  if [ "$1" -eq 1 ]; then
    printf "%s" "$2"
  else
    printf "%s" "$3"
  fi
}


print_operation_duration() {
  local started_at_seconds="$1"

  if [ "$VERBOSE" = "true" ] && can_print_details; then
    local ended_at_seconds
    ended_at_seconds=$(date +%s)
    local elapsed_seconds=$((ended_at_seconds - started_at_seconds))
    print_box_row "   $(print_gray -b "$(icon_prefix "$ICON_TIME")transcurrido=${elapsed_seconds}s")"
    LAST_OUTPUT_WAS_BLANK=false
  fi
}

# Replaces emoji decorations with narrow Unicode symbols (--unicode) or plain
# ASCII (--ascii) for terminals without emoji or Unicode fonts. Texts keep
# their Spanish accents: only decorations change.
apply_icon_mode() {
  case "$ICON_MODE" in
  unicode)
    ICON_APP="" ICON_REAL_RUN="▶" ICON_DRY_RUN="◇" ICON_SOURCE="" ICON_HOME=""
    ICON_GROUP="▸" ICON_CREATED="+" ICON_REPLACED="↻" ICON_UNCHANGED="✓"
    ICON_DELETE="✗" ICON_BACKUP="↺" ICON_DIRECTORY="▪" ICON_SUDO="!"
    ICON_QUEUED="⇢" ICON_WARN="▲" ICON_ERROR="✗" ICON_TIME="" ICON_SUMMARY=""
    ICON_DIAGNOSTIC="" ICON_DONE="✓" ICON_FAILED="✗" ICON_LINKING="⇢"
    RESOLVE_MESSAGE_ICONS=("" "" "" "" "")
    ;;
  ascii)
    ICON_APP="" ICON_REAL_RUN=">" ICON_DRY_RUN="~" ICON_SOURCE="" ICON_HOME=""
    ICON_GROUP=">" ICON_CREATED="+" ICON_REPLACED="~" ICON_UNCHANGED="="
    ICON_DELETE="x" ICON_BACKUP="<" ICON_DIRECTORY="#" ICON_SUDO="!"
    ICON_QUEUED=">" ICON_WARN="!" ICON_ERROR="x" ICON_TIME="" ICON_SUMMARY=""
    ICON_DIAGNOSTIC="" ICON_DONE="=" ICON_FAILED="x" ICON_LINKING=">"
    RESOLVE_MESSAGE_ICONS=("" "" "" "" "")
    BOX_TOP_LEFT="+" BOX_BOTTOM_LEFT="+" BOX_VERTICAL="|" BOX_TEE="+" BOX_HORIZONTAL="-"
    SPINNER_FRAMES=("|" "/" "-" "\\")
    PROGRESS_BAR_FILLED="#" PROGRESS_BAR_EMPTY="."
    POINTER="->" DISPLAY_SEPARATOR="-" DISPLAY_ELLIPSIS="..."
    ;;
  esac
}

set_icon_mode() {
  local requested_mode="$1"
  if [ "$ICON_MODE" != "emoji" ] && [ "$ICON_MODE" != "$requested_mode" ]; then
    log_error_action "Las opciones --ascii y --unicode son excluyentes: usá solo una."
    exit "$EXIT_CODE_INPUT_ERROR"
  fi
  ICON_MODE="$requested_mode"
}

print_help() {
  cat <<'USAGE'
Uso: ./scripts/dotfiler/dotfiler.sh [opciones]

Opciones:
  --dry-run   Muestra los cambios planificados sin escribir archivos
  --no-color  Desactiva los estilos ANSI
  --plain     Desactiva estilos, íconos y énfasis de rutas
  --unicode   Usa símbolos Unicode sin emojis (terminales sin fuente de emojis)
  --ascii     Usa solo ASCII en íconos, cajas y loader (terminales sin Unicode)
  --verbose   Lista también los enlaces sin cambios y el tiempo por operación
  --quiet     Oculta logs por ítem y muestra solo resumen/errores
  --help      Muestra esta ayuda

--unicode y --ascii son excluyentes.

Variables:
  DOTFILER_PROGRESS=auto|always|never  Loader animado (auto: solo en terminal interactiva)
USAGE
}

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
    --dry-run)
      DRY_RUN=true
      ;;
    --no-color)
      USE_COLOR=false
      USE_PATH_STYLE=false
      ;;
    --plain)
      USE_COLOR=false
      USE_ICONS=false
      USE_PATH_STYLE=false
      ;;
    --unicode)
      set_icon_mode "unicode"
      ;;
    --ascii)
      set_icon_mode "ascii"
      ;;
    --verbose)
      VERBOSE=true
      ;;
    --quiet)
      QUIET=true
      ;;
    --help)
      print_help
      exit 0
      ;;
    *)
      log_error_action "Opción desconocida: $1"
      print_help
      exit "$EXIT_CODE_INPUT_ERROR"
      ;;
    esac
    shift
  done
}

record_failed_target() {
  local target="$1"
  local reason="$2"
  printf "%s\t%s\n" "$target" "$reason" >> "$FAILED_TARGETS_FILE"
}

# Counts entries persisted in $FAILED_TARGETS_FILE.
# Used to recover failure counts that were incremented inside command
# substitution subshells (e.g. retrieve_paths_for_platform), where
# changes to COUNT_ERRORS are otherwise lost.
recorded_failure_count() {
  if [ ! -s "$FAILED_TARGETS_FILE" ]; then
    echo 0
    return 0
  fi
  awk 'NF { count++ } END { print count + 0 }' "$FAILED_TARGETS_FILE"
}

validate_paths_config() {
  if [ ! -f "$CONFIG_PATHS_FILE" ]; then
    log_error_action "No se encontró el archivo de configuración: $(print_path "$CONFIG_PATHS_FILE")"
    return 1
  fi

  if ! yq eval '.paths' "$CONFIG_PATHS_FILE" >/dev/null 2>&1; then
    log_error_action "Configuración inválida en $(print_path "$CONFIG_PATHS_FILE"): no se pudo interpretar YAML."
    return 1
  fi

  if ! yq eval -o=json '.paths' "$CONFIG_PATHS_FILE" | jq -e 'type == "array"' >/dev/null 2>&1; then
    log_error_action "Configuración inválida en $(print_path "$CONFIG_PATHS_FILE"): 'paths' debe ser un arreglo."
    return 1
  fi

  return 0
}

# Restrict distro name to a conservative charset to prevent path / PowerShell
# injection when the value flows into the elevated script generation.
SAFE_WSL_DISTRO_REGEX='^[A-Za-z0-9._-]+$'

is_safe_wsl_distro_name() {
  [[ "$1" =~ $SAFE_WSL_DISTRO_REGEX ]]
}

# Get the current WSL distribution name
get_wsl_distro_name() {
  is_wsl || return 0

  local candidate=""

  if [ -n "$WSL_DISTRO_NAME" ]; then
    candidate="$WSL_DISTRO_NAME"
  fi

  if [ -z "$candidate" ]; then
    local win_root
    win_root=$(wslpath -w / 2>/dev/null)
    local distro_regex='^\\\\wsl(\\\\.localhost)?\\\\([^\\\\]+)\\\\'
    if [[ $win_root =~ $distro_regex ]]; then
      candidate="${BASH_REMATCH[2]}"
    fi
  fi

  if [ -z "$candidate" ]; then
    candidate=$(awk -F= '/^NAME=/ { gsub(/"/, "", $2); print $2; exit }' /etc/os-release | tr -d '\r\n')
  fi

  if ! is_safe_wsl_distro_name "$candidate"; then
    log_error_action "Nombre de distribución WSL inválido o inseguro: $candidate"
    return 1
  fi

  echo "$candidate"
}

# Format path for Windows when in WSL
format_wsl_windows_path() {
  local path="$1"
  local distro_name
  if ! distro_name=$(get_wsl_distro_name); then
    return 1
  fi

  if ! is_safe_wsl_distro_name "$distro_name"; then
    log_error_action "Nombre de distribución WSL inválido o inseguro: $distro_name"
    return 1
  fi

  path="\\\\wsl\$\\$distro_name$path"
  path="${path//\//\\}"

  echo "$path"
}

# Returns a backup path that does not collide with an existing entry.
# Mirrors Resolve-BackupPath in dotfiler.ps1 so a previous .bak is never overwritten.
resolve_backup_path() {
  local target="$1"
  local candidate="${target}.bak"
  local suffix=1

  while [ -e "$candidate" ] || [ -L "$candidate" ]; do
    candidate="${target}.bak.${suffix}"
    suffix=$((suffix + 1))
  done

  printf "%s" "$candidate"
}

create_backup() {
  local path="$1"
  shift
  local -a command_prefix=("$@")
  local backup_path
  backup_path=$(resolve_backup_path "$path")

  if [ "$DRY_RUN" = "true" ]; then
    COUNT_BACKUPS=$((COUNT_BACKUPS + 1))
    print_item_line print_yellow "$ICON_BACKUP" "respaldo" "$(basename "$path")" "$POINTER $(basename "$backup_path")"
    return 0
  fi

  if ! "${command_prefix[@]}" mv "${path}" "${backup_path}" 2>/dev/null; then
    log_error_action "No se pudo crear respaldo para $(print_path "$path")"
    record_failed_target "$path" "Fallo al crear respaldo"
    return 1
  fi

  COUNT_BACKUPS=$((COUNT_BACKUPS + 1))
  print_item_line print_yellow "$ICON_BACKUP" "respaldo" "$(basename "$path")" "$POINTER $(basename "$backup_path")"
}

remove_old_symlink() {
  local target="$1"
  shift
  local -a command_prefix=("$@")

  if [ "$DRY_RUN" = "true" ]; then
    return 0
  fi

  if ! "${command_prefix[@]}" rm "$target"; then
    log_error_action "No se pudo eliminar symlink anterior $(print_path "$target")"
    record_failed_target "$target" "Fallo al eliminar symlink anterior"
    return 1
  fi
}

is_home_path() {
  local path="$1"

  [[ -n "$HOME" && ( "$path" == "$HOME" || "$path" == "$HOME/"* ) ]]
}

find_existing_parent_dir() {
  local path="$1"

  while [ ! -d "$path" ] && [ "$path" != "/" ]; do
    path=$(dirname "$path")
  done

  printf "%s" "$path"
}

needs_elevated_permissions() {
  local target="$1"
  local target_dir="$2"

  if ! is_home_path "$target"; then
    return 0
  fi

  if [ -d "$target_dir" ]; then
    [ ! -w "$target_dir" ]
    return $?
  fi

  local existing_parent_dir
  existing_parent_dir=$(find_existing_parent_dir "$target_dir")

  [ ! -w "$existing_parent_dir" ]
}

path_is_inside_configs_dir() {
  local path="$1"
  local resolved_path
  local resolved_configs_dir

  resolved_path=$(realpath "$path" 2>/dev/null) || return 1
  resolved_configs_dir=$(realpath "$ROOT_CONFIGS_DIR" 2>/dev/null) || return 1
  [ "$resolved_path" = "$resolved_configs_dir" ] || [[ "$resolved_path" == "$resolved_configs_dir/"* ]]
}

is_directory_replacement_planned() {
  local target_dir="$1"
  [[ "$PLANNED_DIRECTORY_REPLACEMENTS" == *$'\n'"$target_dir"$'\n'* ]]
}

# Replaces a directory symlink left by a previous run (pointing inside the
# repository configs) with a real directory, and refuses to create links in a
# destination that still resolves inside the repository.
prepare_target_directory() {
  local target_dir="$1"
  shift
  local -a command_prefix=("$@")

  if [ -L "$target_dir" ] && path_is_inside_configs_dir "$target_dir"; then
    local replacement_detail
    replacement_detail="(antes symlink a $(display_source_path "$(realpath "$target_dir")"))"

    if [ "$DRY_RUN" = "true" ]; then
      if ! is_directory_replacement_planned "$target_dir"; then
        PLANNED_DIRECTORY_REPLACEMENTS+="$target_dir"$'\n'
        COUNT_REMOVED=$((COUNT_REMOVED + 1))
        print_item_line print_blue "$ICON_DIRECTORY" "carpeta real" "$(basename "$target_dir")" "$replacement_detail"
      fi
      return 0
    fi

    if ! "${command_prefix[@]}" rm "$target_dir"; then
      log_error_action "No se pudo eliminar symlink de directorio $(print_path "$target_dir")"
      record_failed_target "$target_dir" "Fallo al reemplazar symlink de directorio por carpeta real"
      return 1
    fi
    COUNT_REMOVED=$((COUNT_REMOVED + 1))
    print_item_line print_blue "$ICON_DIRECTORY" "carpeta real" "$(basename "$target_dir")" "$replacement_detail"
    return 0
  fi

  if [ "$DRY_RUN" = "true" ] && is_directory_replacement_planned "$target_dir"; then
    return 0
  fi

  if [ -e "$target_dir" ] && path_is_inside_configs_dir "$target_dir"; then
    log_error_action "El directorio destino resuelve dentro del repositorio: $(print_path "$target_dir")"
    record_failed_target "$target_dir" "Directorio destino dentro del repositorio"
    return 1
  fi
}

# This function creates a symbolic link from the source path to the target location
# It handles existing files by creating backups and removes old symlinks if they exist
make_symlink() {
  local path="$1"
  local target="$2"
  local hard_link="${3:-false}"
  local link_type="$LINK_TYPE_SYMLINK"
  local powershell_link_type="$POWERSHELL_LINK_TYPE_SYMLINK"
  local item_name
  item_name=$(basename "$target")
  local started_at_seconds
  started_at_seconds=$(date +%s)

  if [ "$hard_link" = "true" ]; then
    link_type="$LINK_TYPE_HARD"
    powershell_link_type="$POWERSHELL_LINK_TYPE_HARD"
    if [[ ! "$path" =~ "\\\\wsl\$" ]] && [ ! -f "$path" ]; then
      log_error_action "No se puede crear hard link: el origen no es un archivo regular $(print_path "$path")"
      record_failed_target "$target" "Hard link requiere un archivo regular"
      return 1
    fi
  fi

  local -a command_prefix=()
  local target_dir
  target_dir=$(dirname "$target")

  if needs_elevated_permissions "$target" "$target_dir"; then
    command_prefix=(sudo)
    COUNT_SUDO_OPERATIONS=$((COUNT_SUDO_OPERATIONS + 1))
    print_item_line print_yellow "$ICON_SUDO" "sudo" "$item_name" "(permisos elevados)"
  fi

  if ! prepare_target_directory "$target_dir" "${command_prefix[@]}"; then
    return 1
  fi

  # In dry-run the directory symlink is still in place, so existing entries
  # would be read through it; the replaced directory will start empty.
  local target_dir_pending_replacement="false"
  if [ "$DRY_RUN" = "true" ] && is_directory_replacement_planned "$target_dir"; then
    target_dir_pending_replacement="true"
  fi

  if [ "$target_dir_pending_replacement" != "true" ] && link_is_already_correct "$path" "$target" "$hard_link"; then
    COUNT_UNCHANGED=$((COUNT_UNCHANGED + 1))
    GROUP_UNCHANGED_COUNT=$((GROUP_UNCHANGED_COUNT + 1))
    if [ "$VERBOSE" = "true" ]; then
      print_item_line print_gray "$ICON_UNCHANGED" "sin cambios" "$item_name" "$(print_link_detail "$path" "$link_type")"
      GROUP_CHANGE_COUNT=$((GROUP_CHANGE_COUNT - 1))
    fi
    return 0
  fi

  if [ "$target_dir_pending_replacement" != "true" ] && [ -L "${target}.bak" ]; then
    if ! remove_old_symlink "${target}.bak" "${command_prefix[@]}"; then
      return 1
    fi
    COUNT_REMOVED=$((COUNT_REMOVED + 1))
    print_item_line print_red "$ICON_DELETE" "eliminado" "$item_name.bak" "(symlink de respaldo obsoleto)"
  fi

  local link_action="created"
  if [ "$target_dir_pending_replacement" = "true" ]; then
    COUNT_CREATED=$((COUNT_CREATED + 1))
  elif [ -L "$target" ]; then
    if ! remove_old_symlink "$target" "${command_prefix[@]}"; then
      return 1
    fi
    link_action="replaced"
    COUNT_REPLACED=$((COUNT_REPLACED + 1))
  elif [ -e "$target" ]; then
    if ! create_backup "$target" "${command_prefix[@]}"; then
      return 1
    fi
    link_action="replaced"
    COUNT_REPLACED=$((COUNT_REPLACED + 1))
  else
    COUNT_CREATED=$((COUNT_CREATED + 1))
  fi

  if [ "$DRY_RUN" != "true" ]; then
    if ! "${command_prefix[@]}" mkdir -p "$(dirname "$target")"; then
      log_error_action "No se pudo crear directorio padre para $(print_path "$target")"
      record_failed_target "$target" "Fallo al crear directorio padre"
      return 1
    fi
  fi

  if [[ $path =~ "\\\\wsl\$" ]]; then
    if [ "$DRY_RUN" != "true" ]; then
      local win_target ps_target ps_source
      win_target=$(wslpath -w "$target" 2>/dev/null)
      ps_target="${win_target//\'/\'\'}"
      ps_source="${path//\'/\'\'}"
      echo "New-Item -ItemType $powershell_link_type -Path '$ps_target' -Target '$ps_source' -Force" >> "$TMP_SCRIPT"
    fi
    COUNT_WINDOWS_QUEUED=$((COUNT_WINDOWS_QUEUED + 1))
    print_item_line print_blue "$ICON_QUEUED" "en cola (PS)" "$item_name" "$(print_link_detail "$path" "$link_type")"
  else
    if [ "$DRY_RUN" != "true" ]; then
      local -a link_arguments=()
      if [ "$hard_link" != "true" ]; then
        link_arguments=(-s)
      fi

      if ! "${command_prefix[@]}" ln "${link_arguments[@]}" "$path" "$target"; then
        log_error_action "No se pudo crear $link_type $(print_path "$target") -> $(print_path "${path//\\/\\\\}")"
        record_failed_target "$target" "Fallo al crear $link_type"
        return 1
      fi
    fi
  fi

  if [[ ! $path =~ "\\\\wsl\$" ]]; then
    if [ "$link_action" = "replaced" ]; then
      print_item_line print_blue "$ICON_REPLACED" "reemplazado" "$item_name" "$(print_link_detail "$path" "$link_type")"
    else
      print_item_line print_green "$ICON_CREATED" "creado" "$item_name" "$(print_link_detail "$path" "$link_type")"
    fi
  fi
  print_operation_duration "$started_at_seconds"

  return 0
}

# Removes a symlink left by a previous run whose source is now excluded by an
# active `conditionalExcludes` rule.
remove_stale_symlink() {
  local path="$1"
  local target="$2"
  local reason="${3:-}"
  local -a command_prefix=()
  local item_name
  item_name=$(basename "$target")
  local removal_detail="(excluido por condición)"
  if [ -n "$reason" ]; then
    removal_detail="(excluido por $reason)"
  fi

  if ! symlink_points_to_source "$target" "$path"; then
    return 0
  fi

  if needs_elevated_permissions "$target" "$(dirname "$target")"; then
    command_prefix=(sudo)
    COUNT_SUDO_OPERATIONS=$((COUNT_SUDO_OPERATIONS + 1))
    print_item_line print_yellow "$ICON_SUDO" "sudo" "$item_name" "(permisos elevados)"
  fi

  if [ "$DRY_RUN" != "true" ] && ! "${command_prefix[@]}" rm "$target"; then
    log_error_action "No se pudo eliminar symlink excluido por condición $(print_path "$target")"
    record_failed_target "$target" "Fallo al eliminar symlink excluido por condición"
    return 1
  fi

  COUNT_REMOVED=$((COUNT_REMOVED + 1))
  print_item_line print_red "$ICON_DELETE" "eliminado" "$item_name" "$removal_detail"
}

# True when the destination already is the requested link, so it can be left
# untouched instead of being removed and recreated.
link_is_already_correct() {
  local path="$1"
  local target="$2"
  local hard_link="$3"

  if [[ $path =~ "\\\\wsl\$" ]]; then
    return 1
  fi

  if [ "$hard_link" = "true" ]; then
    [ ! -L "$target" ] && [ -f "$target" ] && [ "$target" -ef "$path" ]
    return $?
  fi

  [ -L "$target" ] && [ "$(readlink "$target")" = "$path" ]
}

# Width of the item name column: longest destination basename, clamped.
resolve_item_name_width() {
  local paths_json="$1"
  local longest_name_length
  longest_name_length=$(echo "$paths_json" | jq '[.[].target | split("/") | last | length] | max // 0')

  if [ "$longest_name_length" -lt "$MIN_ITEM_NAME_WIDTH" ]; then
    longest_name_length=$MIN_ITEM_NAME_WIDTH
  elif [ "$longest_name_length" -gt "$MAX_ITEM_NAME_WIDTH" ]; then
    longest_name_length=$MAX_ITEM_NAME_WIDTH
  fi
  printf "%s" "$longest_name_length"
}

first_letter() {
  echo "${1:0:1}"
}

run_elevated_powershell_script() {
  local tmp_script="$1"
  local started_at_seconds
  started_at_seconds=$(date +%s)

  if ! grep -Eq 'SymbolicLink|HardLink' "$tmp_script"; then
    return 0
  fi

  if [ "$DRY_RUN" = "true" ]; then
    log_info_action "Simulación: se omite la ejecución de PowerShell elevado."
    print_operation_duration "$started_at_seconds"
    return 0
  fi

  local win_tmp_script
  win_tmp_script=$(wslpath -w "$tmp_script")

  if ! powershell.exe -NoProfile -Command "Start-Process PowerShell -ArgumentList '-NoProfile -ExecutionPolicy Bypass -File \"${win_tmp_script}\"' -Verb RunAs -Wait -WindowStyle Hidden"; then
    log_error_action "No se pudo ejecutar el script de PowerShell elevado"
    record_failed_target "powershell_elevado" "Fallo al ejecutar script PowerShell"
    return 1
  fi

  print_operation_duration "$started_at_seconds"
}

# Get Windows username when in WSL
get_windows_username() {
  if ! is_wsl; then
    echo "$USER"
    return 0
  fi

  if [ -f /mnt/c/Windows/System32/cmd.exe ]; then
    /mnt/c/Windows/System32/cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n'
  elif command -v powershell.exe >/dev/null 2>&1; then
    powershell.exe -Command '$env:USERNAME' 2>/dev/null | tr -d '\r'
  elif [ -n "$WSLENV" ] && [ -n "$USERNAME" ]; then
    echo "$USERNAME"
  else
    echo "$USER"
  fi
}

build_path_obj() {
  local path="$1"
  local target="$2"
  local hard_link="${3:-false}"
  local json

  json=$(jq -n \
    --arg path "$path" \
    --arg target "$target" \
    --argjson hardLink "$hard_link" \
    '{path: $path, target: $target, hardLink: $hardLink}')
  echo "$json"
}

json_has_key() {
  local json="$1"
  local key="$2"

  echo "$json" | jq -e --arg key "$key" 'has($key)' >/dev/null 2>&1
}

json_get_value() {
  local json="$1"
  local key="$2"

  echo "$json" | jq -r --arg key "$key" '.[$key]'
}

get_abs_path() {
  local path="$1"

  path=$(expand_env_vars "$path")

  if [ "$(first_letter "$path")" != "/" ] && [ "$(first_letter "$path")" != "~" ]; then
    path="$ROOT_CONFIGS_DIR/$path"
  fi

  realpath "$path" 2>/dev/null || true
}

# Expand environment variables in a path string.
# Only expands `~` when it appears as the leading character so that
# substrings like `archive~backup` are not mangled into `archiveHOMEbackup`.
expand_env_vars() {
  local path="$1"

  path="${path//'$HOME'/$HOME}"
  if [[ "$path" == "~" || "$path" == "~/"* ]]; then
    path="$HOME${path#\~}"
  fi

  if [[ "$path" == /mnt/c/* ]] || [[ "$path" == WSL://* ]]; then
    path="${path//'$USER'/${USERNAME:-$USER}}"
  else
    path="${path//'$USER'/$USER}"
  fi

  echo "$path"
}

add_path_to_output() {
  local path="$1"
  local target="$2"
  local output="$3"
  local uses_exact_target="$4"
  local hard_link="${5:-false}"
  local original_path="$1"
  local selected_target="$target"

  if [ "$uses_exact_target" != "true" ]; then
    selected_target="$target"/"$(basename "$path")"
  fi

  path=$(get_abs_path "$path")
  if [ -z "$path" ]; then
    log_warn_action "Ruta de origen inválida o inexistente: $original_path"
    record_failed_target "$selected_target" "Ruta de origen inexistente"
    echo "$output"
    return 1
  fi

  if [ "$hard_link" = "true" ] && [ ! -f "$path" ]; then
    log_warn_action "No se puede crear hard link: el origen no es un archivo regular $original_path"
    record_failed_target "$selected_target" "Hard link requiere un archivo regular"
    echo "$output"
    return 1
  fi

  if [[ "$selected_target" == WSL://* ]]; then
    selected_target=${selected_target//WSL:\/\//}
    selected_target="/mnt/c/Users/$USERNAME/$selected_target"
    selected_target=$(expand_env_vars "$selected_target")
    if ! path=$(format_wsl_windows_path "$path"); then
      record_failed_target "$selected_target" "Nombre de distribución WSL inválido"
      echo "$output"
      return 1
    fi
  fi

  local path_obj
  path_obj=$(build_path_obj "$path" "$selected_target" "$hard_link")
  echo "$output" | jq -c ". + [$path_obj]"
}

strip_regex_slashes() {
  local p="$1"
  if [ ${#p} -ge 2 ] && [ "${p:0:1}" = "/" ] && [ "${p: -1}" = "/" ]; then
    p="${p:1:${#p}-2}"
  fi
  printf '%s' "$p"
}

validate_regex() {
  local pattern="$1"
  ( [[ "" =~ $pattern ]] ) 2>/dev/null
  local rc=$?
  [ "$rc" -ne 2 ]
}

read_descend_into_pattern() {
  local entry_json="$1"
  local raw
  raw=$(echo "$entry_json" | jq -r '.descendInto // empty')
  [ -z "$raw" ] && return 0
  raw=$(strip_regex_slashes "$raw")
  if ! validate_regex "$raw"; then
    return 1
  fi
  printf '%s' "$raw"
}

read_marker_file() {
  local entry_json="$1"
  echo "$entry_json" | jq -r '.markerFile // empty'
}

read_exclude_pattern() {
  local entry_json="$1"
  local raw
  raw=$(echo "$entry_json" | jq -r '.exclude // empty')
  [ -z "$raw" ] && return 0
  raw=$(strip_regex_slashes "$raw")
  if ! validate_regex "$raw"; then
    return 1
  fi
  printf '%s' "$raw"
}

# Resolves a `whenPathExists` value: expands env vars and treats relative
# paths as relative to $HOME, consistent with how `target` is resolved.
resolve_condition_path() {
  local condition_path="$1"
  condition_path=$(expand_env_vars "$condition_path")
  if [ "$(first_letter "$condition_path")" != "/" ]; then
    condition_path="$HOME/$condition_path"
  fi
  printf '%s' "$condition_path"
}

condition_path_exists() {
  local condition_path
  condition_path=$(resolve_condition_path "$1")
  [ -e "$condition_path" ] || [ -L "$condition_path" ]
}

# Joins non-empty regex patterns into a single ERE alternation.
combine_regex_patterns() {
  local combined=""
  local pattern
  for pattern in "$@"; do
    [ -z "$pattern" ] && continue
    if [ -z "$combined" ]; then
      combined="$pattern"
    else
      combined="($combined)|($pattern)"
    fi
  done
  printf '%s' "$combined"
}

# Prints the combined pattern of every `conditionalExcludes` rule whose
# `whenPathExists` path exists on this machine. Returns 1 on invalid regex.
# Prints a "pattern" line followed by a "whenPathExists" line for every
# `conditionalExcludes` rule active on this machine. Returns 1 on invalid regex.
read_active_conditional_exclude_rules() {
  local entry_json="$1"
  local pattern
  local condition_path

  while IFS= read -r pattern && IFS= read -r condition_path; do
    [ -z "$pattern" ] || [ -z "$condition_path" ] && continue
    pattern=$(strip_regex_slashes "$pattern")
    if ! validate_regex "$pattern"; then
      return 1
    fi
    if condition_path_exists "$condition_path"; then
      printf '%s\n%s\n' "$pattern" "$condition_path"
    fi
  done < <(echo "$entry_json" | jq -r '.conditionalExcludes[]? | (.pattern // ""), (.whenPathExists // "")')
}

combine_conditional_rule_patterns() {
  local active_rules="$1"
  local active_patterns=()
  local pattern
  local condition_path

  while IFS= read -r pattern && IFS= read -r condition_path; do
    [ -z "$pattern" ] && continue
    active_patterns+=("$pattern")
  done <<< "$active_rules"

  combine_regex_patterns "${active_patterns[@]}"
}

# Prints the `whenPathExists` of the first active rule matching the item or
# one of its grouping folders below the glob root.
find_conditional_exclude_reason() {
  local active_rules="$1"
  local root_path="$2"
  local item_path="$3"
  local relative_path="${item_path#"$root_path"/}"
  local segments=()
  local pattern
  local condition_path
  local segment

  IFS='/' read -r -a segments <<< "$relative_path"
  while IFS= read -r pattern && IFS= read -r condition_path; do
    [ -z "$pattern" ] && continue
    for segment in "${segments[@]}"; do
      if [[ "$segment" =~ $pattern ]]; then
        printf '%s' "$condition_path"
        return 0
      fi
    done
  done <<< "$active_rules"
}

folder_should_descend() {
  local name="$1"
  local pat="$2"
  [ -z "$pat" ] && return 1
  [[ "$name" =~ $pat ]]
}

folder_is_excluded() {
  local name="$1"
  local pat="$2"
  [ -z "$pat" ] && return 1
  [[ "$name" =~ $pat ]]
}

leaf_has_marker_file() {
  local dir="$1"
  local marker="$2"
  [ -z "$marker" ] && return 0
  [ -f "$dir/$marker" ]
}

walk_emissions_recursive() {
  local root="$1"
  local descend_pat="$2"
  local exclude_pat="$3"
  local marker="$4"

  [ ! -d "$root" ] && return 0

  local stack=("$root")
  local emissions=()

  while [ ${#stack[@]} -gt 0 ]; do
    local last_index=$((${#stack[@]} - 1))
    local current="${stack[$last_index]}"
    unset 'stack[last_index]'

    local children=()
    local entry
    shopt -s nullglob dotglob
    for entry in "$current"/*; do
      children+=("$entry")
    done
    shopt -u nullglob dotglob

    if [ ${#children[@]} -gt 1 ]; then
      local sorted=()
      local sorted_line
      while IFS= read -r sorted_line; do
        sorted+=("$sorted_line")
      done < <(printf '%s\n' "${children[@]}" | LC_ALL=C sort)
      children=("${sorted[@]}")
    fi

    local child
    for child in "${children[@]}"; do
      local name
      name=$(basename "$child")
      if folder_is_excluded "$name" "$exclude_pat"; then
        continue
      fi
      if [ -d "$child" ] && [ ! -L "$child" ]; then
        if folder_should_descend "$name" "$descend_pat"; then
          stack+=("$child")
          continue
        fi
        if leaf_has_marker_file "$child" "$marker"; then
          emissions+=("$child")
        fi
      else
        emissions+=("$child")
      fi
    done
  done

  if [ ${#emissions[@]} -gt 0 ]; then
    printf '%s\n' "${emissions[@]}" | LC_ALL=C sort
  fi
}

# Lists the sources a glob entry resolves to, applying descendInto,
# exclude and markerFile filters.
list_glob_sources() {
  local abs_dir_path="$1"
  local descend_pat="$2"
  local exclude_pat="$3"
  local marker="$4"

  if [ -n "$descend_pat" ]; then
    walk_emissions_recursive "$abs_dir_path" "$descend_pat" "$exclude_pat" "$marker"
    return 0
  fi

  local item
  while IFS= read -r item; do
    local name
    name=$(basename "$item")
    if folder_is_excluded "$name" "$exclude_pat"; then
      continue
    fi
    if [ -d "$item" ] && [ ! -L "$item" ] && ! leaf_has_marker_file "$item" "$marker"; then
      continue
    fi
    printf '%s\n' "$item"
  done < <(find "$abs_dir_path" -maxdepth 1 -mindepth 1 | LC_ALL=C sort)
}

symlink_points_to_source() {
  local link_path="$1"
  local source_path="$2"

  [ -L "$link_path" ] || return 1
  [ "$(readlink "$link_path")" = "$source_path" ] && return 0
  [ "$(realpath "$link_path" 2>/dev/null)" = "$(realpath "$source_path" 2>/dev/null)" ]
}

path_ends_with_glob_star() {
  local p="$1"
  [[ "$p" == *"/*" ]]
}

process_path_entry() {
  local line="$1"
  local selector_override="$2"

  local path
  path=$(echo "$line" | jq -r '.path')
  local selected_override
  selected_override=$(echo "$line" | jq -c "first(.overrides[]? | select($selector_override)) // empty")
  local target
  local uses_exact_target="false"
  local hard_link
  hard_link=$(echo "$line" | jq -r 'if .hardLink == true then "true" else "false" end')

  if [ -n "$selected_override" ]; then
    if json_has_key "$selected_override" "exactTarget"; then
      target=$(json_get_value "$selected_override" "exactTarget")
      uses_exact_target="true"
    else
      target=$(json_get_value "$selected_override" "target")
    fi
  elif json_has_key "$line" "exactTarget"; then
    target=$(json_get_value "$line" "exactTarget")
    uses_exact_target="true"
  else
    target=$(json_get_value "$line" "target")
  fi

  if [[ "$target" != WSL://* ]]; then
    if [ "$target" = "null" ]; then
      target="$HOME"
    elif [ "$(first_letter "$target")" != "/" ] && [ "$(first_letter "$target")" != "~" ]; then
      target="$HOME"/"$target"
    fi
  fi

  target=$(expand_env_vars "$target")

  local descend_into_pat=""
  local exclude_pat=""
  local conditional_exclude_pat=""
  local active_conditional_rules=""
  local marker_file=""
  local filter_parse_failed="false"

  if descend_into_pat=$(read_descend_into_pattern "$line"); then
    :
  else
    log_warn_action "Patron regex invalido en descendInto para $path"
    record_failed_target "$path" "Patron regex invalido en descendInto"
    filter_parse_failed="true"
  fi

  if exclude_pat=$(read_exclude_pattern "$line"); then
    :
  else
    log_warn_action "Patron regex invalido en exclude para $path"
    record_failed_target "$path" "Patron regex invalido en exclude"
    filter_parse_failed="true"
  fi

  if active_conditional_rules=$(read_active_conditional_exclude_rules "$line"); then
    conditional_exclude_pat=$(combine_conditional_rule_patterns "$active_conditional_rules")
  else
    log_warn_action "Patron regex invalido en conditionalExcludes para $path"
    record_failed_target "$path" "Patron regex invalido en conditionalExcludes"
    filter_parse_failed="true"
  fi

  if [ "$filter_parse_failed" = "true" ]; then
    echo "[]"
    return 0
  fi

  marker_file=$(read_marker_file "$line")

  local has_filters="false"
  if [ -n "$descend_into_pat" ] || [ -n "$exclude_pat" ] || [ -n "$marker_file" ] ||
    json_has_key "$line" "conditionalExcludes"; then
    has_filters="true"
  fi

  if [ "$has_filters" = "true" ] && ! path_ends_with_glob_star "$path"; then
    log_warn_action "descendInto/markerFile/exclude/conditionalExcludes solo aplican con path terminado en '/*'. Ignorando filtros para: $path"
    descend_into_pat=""
    exclude_pat=""
    conditional_exclude_pat=""
    marker_file=""
  fi

  if [ "$uses_exact_target" = "true" ]; then
    conditional_exclude_pat=""
  fi

  local effective_exclude_pat
  effective_exclude_pat=$(combine_regex_patterns "$exclude_pat" "$conditional_exclude_pat")

  if is_debug; then
    echo "Path: $(print_path "${path//\\/\\\\}")" >&2
    echo "Target: $(print_path "$target")" >&2
    echo "-----------" >&2
  fi

  local output="[]"
  local seen_basenames=$'\n'

  add_with_collision_check() {
    local item="$1"
    if [ "$uses_exact_target" = "true" ]; then
      output=$(add_path_to_output "$item" "$target" "$output" "$uses_exact_target" "$hard_link")
      return
    fi
    local base
    base=$(basename "$item")
    if [[ "$seen_basenames" == *$'\n'"$base"$'\n'* ]]; then
      log_warn_action "Colision de basename '$base' para $path (primero gana, descartando $item)"
      record_failed_target "$target/$base" "Colision de basename: $item"
      return
    fi
    seen_basenames+="$base"$'\n'
    output=$(add_path_to_output "$item" "$target" "$output" "$uses_exact_target" "$hard_link")
  }

  # Emits a removal operation for a previously created symlink whose source
  # is now excluded by an active `conditionalExcludes` rule. Only symlinks
  # pointing to that exact source are touched; regular files are never removed.
  add_stale_symlink_removal() {
    local item="$1"
    local base
    base=$(basename "$item")
    if [[ "$seen_basenames" == *$'\n'"$base"$'\n'* ]]; then
      return
    fi
    local link_path="$target/$base"
    if ! symlink_points_to_source "$link_path" "$item"; then
      return
    fi
    local removal_reason
    removal_reason=$(find_conditional_exclude_reason "$active_conditional_rules" "$abs_dir_path" "$item")
    local removal_obj
    removal_obj=$(jq -n --arg path "$item" --arg target "$link_path" --arg reason "$removal_reason" \
      '{path: $path, target: $target, hardLink: false, remove: true, reason: $reason}')
    output=$(echo "$output" | jq -c ". + [$removal_obj]")
  }

  if [[ "$path" == *"*" ]]; then
    local dir_path="${path%/*}"
    local abs_dir_path
    abs_dir_path=$(get_abs_path "$dir_path")

    if [ ! -d "$abs_dir_path" ]; then
      log_warn_action "Directorio no encontrado: $abs_dir_path"
      echo "$output"
      return 0
    fi

    local linked_items=$'\n'
    local item
    while IFS= read -r item; do
      [ -z "$item" ] && continue
      if is_debug; then
        echo "Item: $(print_path "${item//\\/\\\\}")" >&2
        echo "Target: $(print_path "$target")" >&2
        echo "-----------" >&2
      fi
      linked_items+="$item"$'\n'
      add_with_collision_check "$item"
    done < <(list_glob_sources "$abs_dir_path" "$descend_into_pat" "$effective_exclude_pat" "$marker_file")

    if [ -n "$conditional_exclude_pat" ]; then
      while IFS= read -r item; do
        [ -z "$item" ] && continue
        if [[ "$linked_items" == *$'\n'"$item"$'\n'* ]]; then
          continue
        fi
        add_stale_symlink_removal "$item"
      done < <(list_glob_sources "$abs_dir_path" "$descend_into_pat" "$exclude_pat" "$marker_file")
    fi
  else
    output=$(add_path_to_output "$path" "$target" "$output" "$uses_exact_target" "$hard_link")
  fi

  unset -f add_stale_symlink_removal
  unset -f add_with_collision_check
  echo "$output"
}

get_paths() {
  local selector="$1"
  local selector_override="$2"
  local output="[]"
  local entries
  entries=$(yq eval -o=json ".paths[] | select($selector)" "$CONFIG_PATHS_FILE" | jq -c '.')
  local total_entries
  total_entries=$(printf "%s\n" "$entries" | awk 'NF { count++ } END { print count + 0 }')
  local entry_index=0

  while read -r line; do
    [ -z "$line" ] && continue
    entry_index=$((entry_index + 1))
    printf "%s/%s %s\n" "$entry_index" "$total_entries" "$(echo "$line" | jq -r '.path')" > "$RESOLVE_PROGRESS_FILE"
    output=$(echo "$output" | jq -c ". + $(process_path_entry "$line" "$selector_override")")
  done <<< "$entries"

  echo "$output"
}

retrieve_linux_paths() {
  local current_distro
  current_distro=$(get_linux_distro)
  local wsl_status="false"
  if is_wsl; then
    wsl_status="true"
  fi

  local selector='(
    .excludeFor == null or (
      [
        .excludeFor[]? |
        select(
          (
            .platform == null and
            .wsl != null and
            .wsl == '$wsl_status'
          ) or (
            .platform == "linux" and
            (.linuxDistro == null or .linuxDistro == "'$current_distro'")
          )
        )
      ] | length == 0
    )
  ) and (
    .onlyFor == null or (
      [
        .onlyFor[]? |
        select(
          (
            .platform == null and
            .wsl != null and
            .wsl == '$wsl_status'
          ) or (
            .platform == "linux" and
            (.linuxDistro == null or .linuxDistro == "'$current_distro'")
          )
        )
      ] | length > 0
    )
  )'

  local selector_override='((.platform == "linux") and
    (.linuxDistro == null or .linuxDistro == "'$current_distro'")) or
    (.platform == null and .wsl != null and .wsl == '$wsl_status')'

  get_paths "$selector" "$selector_override"
}

retrieve_darwin_paths() {
  local selector='(
    .excludeFor == null or ([.excludeFor[]? | select(.platform == "darwin")] | length == 0)
  ) and (
    .onlyFor == null or ([.onlyFor[]? | select(.platform == "darwin")] | length > 0)
  )'
  local selector_override='.platform == "darwin"'

  get_paths "$selector" "$selector_override"
}

retrieve_paths_for_platform() {
  if is_darwin; then
    retrieve_darwin_paths
  else
    retrieve_linux_paths
  fi
}


print_summary_cell() {
  local icon="$1"
  local label="$2"
  local value="$3"
  printf "%s%s %4s" "$(icon_prefix "$icon")" "$(pad_text "$label" 14)" "$value"
}

print_summary() {
  local end_time_seconds
  end_time_seconds=$(date +%s)
  local total_elapsed_seconds=$((end_time_seconds - START_TIME_SECONDS))
  local column_gap="     "
  local mode_text="$(icon_prefix "$ICON_REAL_RUN")aplicación real"
  if [ "$DRY_RUN" = "true" ]; then
    mode_text="$(icon_prefix "$ICON_DRY_RUN")simulación, no se escribieron cambios"
  fi

  local errors_cell
  errors_cell=$(print_summary_cell "$ICON_ERROR" "errores" "$COUNT_ERRORS")
  if [ "$COUNT_ERRORS" -gt 0 ]; then
    errors_cell=$(print_red -b "$errors_cell")
  fi

  local status_text
  if [ "$COUNT_ERRORS" -eq 0 ]; then
    status_text=$(print_green -b "$(icon_prefix "$ICON_DONE")Sin errores.")
  else
    status_text=$(print_red -b "$(icon_prefix "$ICON_FAILED")Finalizado con $COUNT_ERRORS error(es).")
  fi

  print_block_gap
  print_box_top "$(icon_prefix "$ICON_SUMMARY")Resumen"
  print_box_row "$(print_green -b "$(print_summary_cell "$ICON_CREATED" "creados" "$COUNT_CREATED")")$column_gap$(print_blue -b "$(print_summary_cell "$ICON_REPLACED" "reemplazados" "$COUNT_REPLACED")")"
  print_box_row "$(print_summary_cell "$ICON_UNCHANGED" "sin cambios" "$COUNT_UNCHANGED")$column_gap$(print_summary_cell "$ICON_DELETE" "eliminados" "$COUNT_REMOVED")"
  print_box_row "$(print_summary_cell "$ICON_BACKUP" "respaldos" "$COUNT_BACKUPS")$column_gap$errors_cell"
  if [ "$COUNT_SUDO_OPERATIONS" -gt 0 ] || [ "$COUNT_WINDOWS_QUEUED" -gt 0 ]; then
    print_box_row "$(print_summary_cell "$ICON_SUDO" "con sudo" "$COUNT_SUDO_OPERATIONS")$column_gap$(print_summary_cell "$ICON_QUEUED" "Windows (PS)" "$COUNT_WINDOWS_QUEUED")"
  fi
  print_box_divider
  print_box_row "$mode_text $(print_gray -b "$DISPLAY_SEPARATOR") $(icon_prefix "$ICON_TIME")${total_elapsed_seconds}s $(print_gray -b "$DISPLAY_SEPARATOR") $status_text"
  print_box_bottom
  LAST_OUTPUT_WAS_BLANK=false
}

print_diagnostics() {
  if [ ! -s "$FAILED_TARGETS_FILE" ]; then
    return 0
  fi

  print_block_gap
  print_box_top "$(icon_prefix "$ICON_DIAGNOSTIC")Diagnóstico"

  local diagnostic_index=1
  while IFS=$'\t' read -r failed_target failed_reason; do
    [ -z "$failed_target" ] && continue
    print_box_row "$(print_red -b "$diagnostic_index.") $(print_path "$(display_target_path "$failed_target")")"
    print_box_row "   $(print_gray -b "$POINTER $failed_reason")"
    diagnostic_index=$((diagnostic_index + 1))
  done < "$FAILED_TARGETS_FILE"
  print_box_bottom
  LAST_OUTPUT_WAS_BLANK=false
}

print_banner() {
  can_print_details || return 0

  local mode_text="$(icon_prefix "$ICON_REAL_RUN")aplicación real"
  if [ "$DRY_RUN" = "true" ]; then
    mode_text="$(icon_prefix "$ICON_DRY_RUN")simulación: no se escriben cambios"
  fi

  print_box_top ""
  print_box_row "$(print_magenta -b "$(icon_prefix "$ICON_APP")dotfiler") $(print_gray -b "$DISPLAY_SEPARATOR") $mode_text"
  print_box_row "$(print_gray -b "$(icon_prefix "$ICON_SOURCE")$(display_target_path "$ROOT_CONFIGS_DIR")  $POINTER  $(icon_prefix "$ICON_HOME")~")"
  print_box_bottom
  LAST_OUTPUT_WAS_BLANK=false
}

main() {
  parse_args "$@"
  apply_icon_mode

  check_commands yq jq
  if ! validate_paths_config; then
    print_diagnostics
    return "$EXIT_CODE_INPUT_ERROR"
  fi

  USERNAME=$(get_windows_username)

  print_banner

  local paths
  start_spinner
  paths="$(retrieve_paths_for_platform)"
  stop_spinner
  local last_group=""
  ITEM_NAME_WIDTH=$(resolve_item_name_width "$paths")
  local total_operations
  total_operations=$(echo "$paths" | jq 'length')
  local operation_index=0
  if progress_is_enabled; then
    printf "\033[?25l" >&2
  fi

  while read -r line; do
    if [ -z "$line" ]; then
      continue
    fi

    local path
    path=$(echo "$line" | jq -r '.path')
    local target
    target=$(echo "$line" | jq -r '.target')
    local hard_link
    hard_link=$(echo "$line" | jq -r 'if .hardLink == true then "true" else "false" end')
    local remove_link
    remove_link=$(echo "$line" | jq -r 'if .remove == true then "true" else "false" end')
    local removal_reason
    removal_reason=$(echo "$line" | jq -r '.reason // empty')
    operation_index=$((operation_index + 1))
    render_linking_progress "$operation_index" "$total_operations" "$(basename "$target")"

    local current_group
    current_group=$(display_target_path "$(dirname "$target")")

    if [ "$current_group" != "$last_group" ]; then
      flush_group_unchanged_count
      print_group_header "$current_group"
      last_group="$current_group"
    fi

    if [ "$remove_link" = "true" ]; then
      if ! remove_stale_symlink "$path" "$target" "$removal_reason"; then
        COUNT_ERRORS=$((COUNT_ERRORS + 1))
      fi
    elif ! make_symlink "$path" "$target" "$hard_link"; then
      COUNT_ERRORS=$((COUNT_ERRORS + 1))
    fi
  done < <(echo "$paths" | jq -c "$SORT_BY_TARGET_GROUP_FILTER")

  flush_group_unchanged_count
  stop_spinner

  if [ "$COUNT_UNCHANGED" -gt 0 ] && [ "$VERBOSE" != "true" ] && can_print_details &&
    [ $((COUNT_CREATED + COUNT_REPLACED + COUNT_REMOVED + COUNT_BACKUPS + COUNT_WINDOWS_QUEUED)) -eq 0 ]; then
    print_block_gap
    printf "%s\n" "$(print_green -b "$(icon_prefix "$ICON_UNCHANGED")Todos los enlaces están al día ($COUNT_UNCHANGED).")"
    LAST_OUTPUT_WAS_BLANK=false
  fi

  if ! run_elevated_powershell_script "$TMP_SCRIPT"; then
    COUNT_ERRORS=$((COUNT_ERRORS + 1))
  fi

  # Reconcile errors recorded inside command substitution subshells
  # (e.g. add_path_to_output during retrieve_paths_for_platform) so that
  # the summary and exit code reflect failures that the in-process
  # COUNT_ERRORS counter could not observe.
  local recorded_failures
  recorded_failures=$(recorded_failure_count)
  if [ "$recorded_failures" -gt "$COUNT_ERRORS" ]; then
    COUNT_ERRORS="$recorded_failures"
  fi

  print_summary
  print_diagnostics

  if [ "$COUNT_ERRORS" -gt 0 ]; then
    return "$EXIT_CODE_RUNTIME_ERROR"
  fi

  return "$EXIT_CODE_SUCCESS"
}

if [ "$EUID" = 0 ]; then
  log_error_action "No ejecutes este script como root."
  exit "$EXIT_CODE_INPUT_ERROR"
fi

main "$@"
