[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']

[custom-keybindings/custom0]
binding='<Super>w'
command='wezterm'
name='Launch WezTerm'

[custom-keybindings/custom1]
binding='<Super>e'
command='nautilus .'
name='Launch Home'

[custom-keybindings/custom2]
binding='<Super>b'
command='microsoft-edge-stable'
name='Launch Browser'
