#!/bin/sh

PIDs=$(ps ax | grep xautolock | grep -v 'pts/[0-9]' | awk '{print $1}')

# while read -r pid; do
# 	notify-send -- xautolock "PID: $pid"
# done<<<"$PIDs"

if [[ -n "$PIDs" ]]; then
	notify-send -- xautolock Initialized
	notify_time=30

	xautolock -detectsleep \
		-time 3 \
		-locker "~/.config/scripts/lockBlur" \
		-notify $notify_time \
		-notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in $notify_time seconds'"
fi
