source "$ZSH_HOME/.antigenrc"
source "$ZSH_HOME/aliases.zsh"
source "$ZSH_HOME/completions.zsh"
source "$ZSH_HOME/functions.zsh"
source "$ZSH_HOME/mappings.zsh"
source "$ZSH_HOME/paths.zsh"
source "$ZSH_HOME/plugins.zsh"
source "$ZSH_HOME/settings/init.zsh"
