matches:
  - triggers: ["@@", "@todo"]
    force_clipboard: true
    label: "TODO"
    replace: "[📝 TO DO]"
  - triggers: ["@@", "@wip"]
    force_clipboard: true
    label: "Work in Progress"
    replace: "[🚧 WIP]"
  - triggers: ["@@", "@done"]
    force_clipboard: true
    label: "Done"
    replace: "[✅ DONE]"
  - triggers: ["@@", "@hold"]
    force_clipboard: true
    label: "On Hold"
    replace: "[⏸️ ON HOLD]"
  - triggers: ["@@", "@prev"]
    force_clipboard: true
    label: "Pending Review"
    replace: "[👀 PENDING REVIEW]"
  - triggers: ["@@", "@pfrev"]
    force_clipboard: true
    label: "Pending Final Review"
    replace: "[👀 PENDING FINAL REVIEW]"
  - triggers: ["@@", "@revreq"]
    force_clipboard: true
    label: "Review Requested"
    replace: "[👀 REVIEW REQUESTED]"
  - triggers: ["@@", "@unrev"]
    force_clipboard: true
    label: "Under Review"
    replace: "[🔍 UNDER REVIEW]"
  - triggers: ["@@", "@reqch"]
    force_clipboard: true
    label: "Request Changes"
    replace: "[🔄 REQUEST CHANGES]"
  - triggers: ["@@", "@merge"]
    force_clipboard: true
    label: "Ready to Merge"
    replace: "[🔀 READY TO MERGE]"
  - triggers: ["@@", "@closed"]
    force_clipboard: true
    label: "Closed"
    replace: "[🔒 CLOSED]"
  - triggers: ["@@", "@block"]
    force_clipboard: true
    label: "Blocked"
    replace: "[⛔ BLOCKED]"
  - triggers: ["@@", "@ans"]
    force_clipboard: true
    label: "Answered Comments"
    replace: "[💬 ANSWERED COMMENTS]"
  - triggers: ["@@", "@app"]
    force_clipboard: true
    label: "Approved PR"
    replace: "[🟢 APPROVED]"
  - triggers: ["@@", "@comm"]
    force_clipboard: true
    label: "Add Comments"
    replace: "[💬 ADDED COMMENTS]"
  - triggers: ["@@", "@test"]
    force_clipboard: true
    label: "Tested"
    replace: "[🧪 TESTED]"
  - triggers: ["@@", "@needtest"]
    force_clipboard: true
    label: "Need Testing"
    replace: "[🧪 NEED TESTING]"
  - triggers: ["@@", "@doc"]
    force_clipboard: true
    label: "Documented"
    replace: "[📚 DOCUMENTED]"
  - triggers: ["@@", "@needdoc"]
    force_clipboard: true
    label: "Need Documentation"
    replace: "[📚 NEED DOCUMENTATION]"
  - triggers: ["@@", "@solved"]
    force_clipboard: true
    label: "Solved Comments"
    replace: "[✅ SOLVED COMMENTS]"
  - triggers: ["@@", "@failtest"]
    force_clipboard: true
    label: "Tests Failed"
    replace: "[❌ TESTS FAILED]"
  - triggers: ["@@", "@fixtest"]
    force_clipboard: true
    label: "Fix Tests"
    replace: "[🔧 FIX TESTS]"
  - triggers: ["@@", "@wfs"]
    force_clipboard: true
    label: "Waiting for Solved"
    replace: "[⏳ WAITING FOR SOLVED]"
  - triggers: ["@@", "@prmer"]
    force_clipboard: true
    label: "PR Merged"
    replace: "[🔀 PR MERGED]"
  - triggers: ["@@", "@ans"]
    force_clipboard: true
    label: "Community Answered"
    replace: "[👥 ANSWERED]"
  - triggers: ["@@", "@closed"]
    force_clipboard: true
    label: "Community Closed"
    replace: "[👥 CLOSED]"
  - triggers: ["@@", "@notplan"]
    force_clipboard: true
    label: "Community Closed as Not Planned"
    replace: "[👥 CLOSED AS NOT PLANNED]"
  - triggers: ["@@", "@askteam"]
    force_clipboard: true
    label: "Asked Team"
    replace: "[👥 ASKED TEAM]"
  - triggers: ["@@", "@invest"]
    force_clipboard: true
    label: "Investigating"
    replace: "[🔎 INVESTIGATING]"
