matches:
  - triggers: [";wstatus", ";prev"]
    label: "Pending Review"
    force_clipboard: true
    replace: |
      :github: PENDING REVIEW 👀
      -
  - triggers: [";wstatus", ";change"]
    label: "Request Changes"
    force_clipboard: true
    replace: |
      :github: REQUEST CHANGES 🔧
      -
  - triggers: [";wstatus", ";pfrev"]
    label: "Pending Final Review"
    force_clipboard: true
    replace: |
      :github: PENDING FINAL REVIEW 👀 (✅☑️ 1 of 2 approvals)
      -
  - triggers: [";wstatus", ";mer"]
    label: "Ready to Merge"
    force_clipboard: true
    replace: |
      :github: READY TO MERGE 🔀
      -
