matches:
  - triggers: ["%task", "%todo"]
    force_clipboard: true
    label: "TODO"
    replace: "[📝 TO DO]"
  - triggers: ["%task", "%wip"]
    force_clipboard: true
    label: "Work in Progress"
    replace: "[🚧 WIP]"
  - triggers: ["%task", "%done"]
    force_clipboard: true
    label: "Done"
    replace: "[✅ DONE]"
  - triggers: ["%task", "%hold"]
    force_clipboard: true
    label: "On Hold"
    replace: "[⏸️ ON HOLD]"
  - triggers: ["%task", "%prev"]
    force_clipboard: true
    label: "Pending Review"
    replace: "[👀 PENDING REVIEW]"
  - triggers: ["%task", "%pfrev"]
    force_clipboard: true
    label: "Pending Final Review"
    replace: "[👀 PENDING FINAL REVIEW]"
  - triggers: ["%task", "%revreq"]
    force_clipboard: true
    label: "Review Requested"
    replace: "[👀 REVIEW REQUESTED]"
  - triggers: ["%task", "%unrev"]
    force_clipboard: true
    label: "Under Review"
    replace: "[🔍 UNDER REVIEW]"
  - triggers: ["%task", "%reqch"]
    force_clipboard: true
    label: "Request Changes"
    replace: "[🔄 REQUEST CHANGES]"
  - triggers: ["%task", "%merge"]
    force_clipboard: true
    label: "Ready to Merge"
    replace: "[🔀 READY TO MERGE]"
  - triggers: ["%task", "%closed"]
    force_clipboard: true
    label: "Closed"
    replace: "[🔒 CLOSED]"
  - triggers: ["%task", "%block"]
    force_clipboard: true
    label: "Blocked"
    replace: "[⛔ BLOCKED]"
  - triggers: ["%task", "%ans"]
    force_clipboard: true
    label: "Answered Comments"
    replace: "[💬 ANSWERED COMMENTS]"
  - triggers: ["%task", "%app"]
    force_clipboard: true
    label: "Approved PR"
    replace: "[🟢 APPROVED]"
  - triggers: ["%task", "%comm"]
    force_clipboard: true
    label: "Add Comments"
    replace: "[💬 ADDED COMMENTS]"
  - triggers: ["%task", "%test"]
    force_clipboard: true
    label: "Tested"
    replace: "[🧪 TESTED]"
  - triggers: ["%task", "%needtest"]
    force_clipboard: true
    label: "Need Testing"
    replace: "[🧪 NEED TESTING]"
  - triggers: ["%task", "%doc"]
    force_clipboard: true
    label: "Documented"
    replace: "[📚 DOCUMENTED]"
  - triggers: ["%task", "%needdoc"]
    force_clipboard: true
    label: "Need Documentation"
    replace: "[📚 NEED DOCUMENTATION]"
  - triggers: ["%task", "%solved"]
    force_clipboard: true
    label: "Solved Comments"
    replace: "[✅ SOLVED COMMENTS]"
  - triggers: ["%task", "%failtest"]
    force_clipboard: true
    label: "Tests Failed"
    replace: "[❌ TESTS FAILED]"
  - triggers: ["%task", "%fixtest"]
    force_clipboard: true
    label: "Fix Tests"
    replace: "[🔧 FIX TESTS]"
  - triggers: ["%task", "%wfs"]
    force_clipboard: true
    label: "Waiting for Solved"
    replace: "[⏳ WAITING FOR SOLVED]"
  - triggers: ["%task", "%prmer"]
    force_clipboard: true
    label: "PR Merged"
    replace: "[🔀 PR MERGED]"
  - triggers: ["%task", "%ans"]
    force_clipboard: true
    label: "Community Answered"
    replace: "[👥 ANSWERED]"
  - triggers: ["%task", "%closed"]
    force_clipboard: true
    label: "Community Closed"
    replace: "[👥 CLOSED]"
  - triggers: ["%task", "%notplan"]
    force_clipboard: true
    label: "Community Closed as Not Planned"
    replace: "[👥 CLOSED AS NOT PLANNED]"
  - triggers: ["%task", "%askteam"]
    force_clipboard: true
    label: "Asked Team"
    replace: "[👥 ASKED TEAM]"
  - triggers: ["%task", "%invest"]
    force_clipboard: true
    label: "Investigating"
    replace: "[🔎 INVESTIGATING]"
