matches:
  - triggers: [";lg"]
    label: "LGTM"
    force_clipboard: true
    replace: |
      LGTM! {{green_circle}}
  - triggers: [";test", ";check"]
    label: "Code Review and Test"
    force_clipboard: true
    replace: |
      {{legend}}

      # 🧪 Test {{short_date}}

      CR {{black_circle}}
      TEST {{black_circle}}
  - triggers: [";test", ";utest"]
    label: "Unit Test"
    force_clipboard: true
    replace: |
      <details><summary>{{black_circle}} $|$</summary>
        <br />

        > **CHROME** - {{black_circle}}
        >
        >

        > **FIREFOX** - {{black_circle}}
        >
        >

      </details>
  - triggers: [";test", ";tcc"]
    label: "Chrome"
    force_clipboard: true
    replace: |
        > **CHROME** - {{black_circle}}
        >
        >
  - triggers: [";test", ";tff"]
    label: "Firefox"
    force_clipboard: true
    replace: |
        > **FIREFOX** - {{black_circle}}
        >
        >
