matches:
  - triggers: [";wk", ";wt"]
    label: "[Work thread]"
    force_clipboard: true
    replace: "Good morning! Work thread :thread:"
  - triggers: [";wk", ";wdaily"]
    label: "Daily Report"
    force_clipboard: true
    replace: |
      # Guido Modarelli - {{short_date}}

      ## Development

      ### Worked on

      *

      ### Reviews

      *

      ## Miscellaneous

      *
